import { defineDict } from "../../../lib/dict";

export const INTEGRATIONS = defineDict(
  {
    intro:
      "سرویس‌های بیرونی در سطح سازمان. اطلاعات ورود رمزنگاری‌شده ذخیره می‌شود، هرگز نمایش داده نمی‌شود و پیش از ذخیره، زنده آزموده می‌شود.",
    owner_only: "فقط مالک یا مدیر سازمان می‌تواند سرویس‌ها را تنظیم کند.",
    connected: "وصل",
    not_connected: "وصل نیست",
    error: "خطا",
    last_checked: "آخرین بررسی {when}",
    test: "آزمودن دوباره",
    remove: "حذف",
    save_connect: "آزمودن و ذخیره",
    replace: "جایگزینی اطلاعات ورود",
    ok_saved: "وصل شد و ذخیره شد.",
    ok_tested: "آزمون موفق بود.",
    // DataForSEO
    dfs_title: "DataForSEO",
    dfs_desc:
      "حجم جستجو، سختی کلمه، رتبه‌ی زنده در گوگل، شکاف کلمات با رقبا و بک‌لینک‌ها. پرداخت به ازای هر درخواست؛ هزینه‌ی هر درخواست ثبت و اینجا جمع زده می‌شود.",
    dfs_login: "نام کاربری (ایمیل حساب)",
    dfs_password: "رمز API",
    dfs_password_help: "رمز API از داشبورد DataForSEO، نه رمز ورود به سایت آن.",
    dfs_rank: "بررسی روزانه‌ی رتبه‌ی زنده برای کلمه‌های ردیابی‌شده",
    dfs_rank_help: "هر کلمه در هر روز یک درخواست پولی است.",
    dfs_cap: "سقف بررسی رتبه در روز برای هر پروژه",
    dfs_account: "حساب",
    dfs_balance: "موجودی",
    dfs_settings_save: "ذخیره‌ی تنظیمات",
    usage_title: "هزینه‌ی ۳۰ روز اخیر",
    usage_total: "مجموع: {n} دلار در {c} درخواست",
    usage_endpoint: "سرویس",
    usage_calls: "درخواست",
    usage_cost: "هزینه (دلار)",
    usage_none: "هنوز درخواست پولی‌ای ثبت نشده.",
    // PageSpeed
    psi_title: "کلید PageSpeed Insights",
    psi_desc: "سنجش سرعت بدون کلید هم کار می‌کند اما با سهمیه‌ی مشترک و کم گوگل. کلید رایگان سهمیه را بالا می‌برد.",
    psi_key: "کلید API گوگل",
    psi_key_help: "در `Google Cloud` یک کلید API بساز و PageSpeed Insights API را برایش فعال کن.",
    psi_hint: "کلید ذخیره‌شده: {hint}",
    // Telegram
    tg_title: "هشدار تلگرام",
    tg_desc: "هشدارها را در یک گروه یا کانال تلگرام بفرست. ربات را با `BotFather` بساز و به گروه یا کانال اضافه کن.",
    tg_token: "توکن ربات",
    tg_chat: "شناسه‌ی چت یا نام کانال",
    tg_chat_help: "شناسه‌ی عددی گروه (منفی) یا نام کانال با @.",
    tg_bot: "ربات",
    tg_chat_title: "چت",
    tg_test_help: "آزمودن دوباره یک پیام آزمایشی به همان چت می‌فرستد.",
  },
  {
    intro:
      "Outside services for the whole organization. Credentials are stored encrypted, never shown again, and tested live before they are saved.",
    owner_only: "Only an owner or admin of the organization can set up integrations.",
    connected: "Connected",
    not_connected: "Not connected",
    error: "Error",
    last_checked: "Last checked {when}",
    test: "Test again",
    remove: "Remove",
    save_connect: "Test and save",
    replace: "Replace credentials",
    ok_saved: "Connected and saved.",
    ok_tested: "The test succeeded.",
    dfs_title: "DataForSEO",
    dfs_desc:
      "Search volume, keyword difficulty, live Google rankings, keyword gap against competitors and backlinks. Pay per request; each request's cost is recorded and totalled here.",
    dfs_login: "Login (account email)",
    dfs_password: "API password",
    dfs_password_help: "The API password from the DataForSEO dashboard, not the password for their website.",
    dfs_rank: "Daily live rank checks for tracked keywords",
    dfs_rank_help: "Each keyword each day is one paid request.",
    dfs_cap: "Daily rank-check cap per project",
    dfs_account: "Account",
    dfs_balance: "Balance",
    dfs_settings_save: "Save settings",
    usage_title: "Spend, last 30 days",
    usage_total: "Total: ${n} over {c} requests",
    usage_endpoint: "Service",
    usage_calls: "Requests",
    usage_cost: "Cost (USD)",
    usage_none: "No paid request recorded yet.",
    psi_title: "PageSpeed Insights key",
    psi_desc: "Speed checks work without a key, on Google's small shared quota. A free key raises it.",
    psi_key: "Google API key",
    psi_key_help: "In Google Cloud, create an API key and enable the PageSpeed Insights API for it.",
    psi_hint: "Stored key: {hint}",
    tg_title: "Telegram alerts",
    tg_desc: "Send alerts to a Telegram group or channel. Create a bot with BotFather and add it to the group or channel.",
    tg_token: "Bot token",
    tg_chat: "Chat id or channel name",
    tg_chat_help: "A group's numeric id (negative) or a channel name with @.",
    tg_bot: "Bot",
    tg_chat_title: "Chat",
    tg_test_help: "Testing again sends a test message to the same chat.",
  },
);

export type IntegrationStrings = (typeof INTEGRATIONS)["fa"];
