import { defineDict } from "../../../lib/dict";

/**
 * Wording of the Instagram / Telegram screens. Keys ending in _IG / _TG are
 * picked by the project's platform; `backticks` are set as code (Rich).
 */
export const SOCIAL = defineDict(
  {
    // ---------------------------------------------------------------- shared
    platform_INSTAGRAM: "اینستاگرام",
    platform_TELEGRAM: "تلگرام",
    page_IG: "صفحه‌ی اینستاگرام",
    page_TG: "کانال تلگرام",
    st_CONNECTED: "وصل",
    st_NOT_CONNECTED: "وصل نیست",
    st_ERROR: "خطای اتصال",
    src_api_IG: "API اینستاگرام",
    src_api_TG: "API ربات تلگرام",
    src_public_preview: "پیش‌نمایش عمومی تلگرام",
    src_business_discovery: "جست‌وجوی حساب‌های حرفه‌ای اینستاگرام",
    src_help_api_IG: "عدد را خود اینستاگرام با اجازه‌ی صاحب صفحه گزارش کرده است.",
    src_help_api_TG: "عدد را خود تلگرام به ربات مدیر کانال گزارش کرده است.",
    src_help_public_preview: "از صفحه‌ی عمومی کانال خوانده شده و مثل خود تلگرام گرد شده است (مثلاً ۱٫۲ هزار).",
    not_connected_title_IG: "صفحه‌ی اینستاگرام هنوز وصل نیست",
    not_connected_title_TG: "کانال تلگرام هنوز وصل نیست",
    not_connected_body: "تا حساب وصل نشود، هیچ عددی نمایش داده نمی‌شود. اتصال یک بار انجام می‌شود و بعد همگام‌سازی روزانه خودکار است.",
    go_connect: "رفتن به اتصال",
    no_social_project: "این صفحه برای پروژه‌های اینستاگرام و تلگرام است.",
    sev_CRITICAL: "بحرانی",
    sev_SERIOUS: "جدی",
    sev_WARNING: "هشدار",
    sev_INFO: "اطلاع",
    followers_IG: "دنبال‌کننده",
    followers_TG: "عضو",
    unknown_reason: "خطای ناشناخته از پلتفرم.",
    open_on_platform_IG: "باز کردن در اینستاگرام",
    open_on_platform_TG: "باز کردن در تلگرام",
    no_permission: "نقش شما اجازه‌ی این کار را ندارد.",

    // ---------------------------------------------------------------- overview
    ov_intro_IG:
      "وضعیت صفحه‌ی اینستاگرام: اتصال، امتیاز ممیزی، شاخص‌های اصلی و هدف‌گذاری. همه‌ی عددها همان‌هایی است که اینستاگرام گزارش کرده؛ چیزی تخمین زده نمی‌شود.",
    ov_intro_TG:
      "وضعیت کانال تلگرام: اتصال ربات، امتیاز ممیزی، شاخص‌های اصلی و هدف‌گذاری. تعداد اعضا از ربات و بازدیدها از پیش‌نمایش عمومی تلگرام می‌آید.",
    ig_connected: "اینستاگرام وصل شد. همگام‌سازی اول در جریان است.",
    ig_failed: "اتصال اینستاگرام انجام نشد:",
    sync_now: "همگام‌سازی",
    syncing: "در حال همگام‌سازی…",
    sync_done: "همگام‌سازی تمام شد و داده‌ها تازه شدند.",
    sync_failed: "همگام‌سازی ناموفق بود:",
    sync_slow: "همگام‌سازی هنوز در جریان است؛ نتیجه پس از پایان اینجا دیده می‌شود.",
    check: "بررسی اتصال",
    check_ok: "اتصال سالم است و دسترسی‌ها تازه شد.",
    check_failed: "بررسی اتصال:",
    disconnect: "قطع اتصال",
    disconnect_confirm: "قطع شود؟",
    disconnected: "اتصال قطع شد: توکن پاک شد و تاریخچه، ممیزی‌ها و برنامه‌ها باقی ماند.",
    disconnect_help: "صفحه یا کانال دست نمی‌خورد؛ فقط پنل دیگر به آن دسترسی ندارد.",
    last_sync: "آخرین همگام‌سازی",
    never: "هنوز نه",
    connected_at: "وصل از",
    token_expires: "اعتبار اتصال تا",
    token_renew_help: "هر بار همگام‌سازی، اتصال را پیش از انقضا تمدید می‌کند.",
    account_type: "نوع حساب",
    acct_BUSINESS: "کسب‌وکار",
    acct_MEDIA_CREATOR: "تولیدکننده‌ی محتوا",
    updates_mode: "دریافت پست‌های تازه",
    mode_webhook: "لحظه‌ای",
    mode_polling: "در هر همگام‌سازی",
    webhook_failed: "ثبت دریافت لحظه‌ای ناموفق بود؛ پست‌های تازه در همگام‌سازی بعدی خوانده می‌شوند.",
    bot: "ربات مدیر",
    rights: "دسترسی‌های ربات",
    right_can_post_messages: "ارسال پیام",
    right_can_edit_messages: "ویرایش پیام‌های دیگران",
    right_can_change_info: "تغییر اطلاعات کانال",
    right_can_pin_messages: "سنجاق کردن پیام",
    right_use_can_post_messages: "انتشار پست‌های برنامه‌ریزی‌شده",
    right_use_can_edit_messages: "ویرایش و سنجاق کردن پست‌ها",
    right_use_can_change_info: "اعمال عنوان و توضیحات پیشنهادی، پس از تأیید شما",
    right_missing: "ندارد",
    right_ok: "دارد",
    no_bio: "بدون توضیحات",
    website: "لینک",
    score: "امتیاز صفحه",
    score_help: "۱۰۰ منهای وزن هر یافته بر اساس شدت: بحرانی ۲۰، جدی ۱۲، هشدار ۶، اطلاع ۲.",
    no_audit: "هنوز ممیزی انجام نشده است.",
    run_audit: "ممیزی همین حالا",
    auditing: "در حال ممیزی…",
    audit_done: "ممیزی انجام شد: امتیاز {score}، {n} یافته.",
    findings_n: "{n} یافته",
    view_findings: "دیدن یافته‌ها",
    metrics: "شاخص‌های ۲۸ روز اخیر",
    m_followers_IG: "دنبال‌کنندگان",
    m_followers_TG: "اعضا",
    m_change: "{n} در این بازه",
    m_change_pct: "{n}٪",
    m_posts_week: "پست در هفته",
    m_posts_n: "{n} پست در این بازه",
    m_er_reach: "نرخ تعامل بر پایه‌ی دسترسی",
    m_er_followers: "نرخ تعامل بر پایه‌ی دنبال‌کننده",
    m_avg_views: "میانگین بازدید هر پست",
    m_view_rate: "نرخ بازدید",
    m_no_data: "داده‌ای نیست",
    m_no_change: "برای تغییر، دست‌کم دو روز داده لازم است",
    caps_title: "این اتصال چه می‌تواند بکند",
    cap_edit_profile_IG: "ویرایش نام، بیو و لینک پروفایل",
    cap_edit_profile_TG: "تغییر عنوان و توضیحات کانال (پس از تأیید)",
    cap_publish: "انتشار پست",
    cap_edit_posts: "ویرایش پست‌های منتشرشده",
    cap_pin: "سنجاق کردن پیام",
    cap_competitors: "آمار رقبا",
    cap_views_TG: "آمار بازدید پست‌ها",
    cap_yes: "بله",
    cap_no: "خیر",
    cap_unknown: "هنوز معلوم نیست",
    note_instagram_profile_manual:
      "API اینستاگرام اجازه‌ی ویرایش نام، بیو و لینک پروفایل را نمی‌دهد؛ پنل متن پیشنهادی آماده می‌کند و شما آن را در اپ جایگزین می‌کنید.",
    note_instagram_competitors_business_discovery:
      "آمار رقبا از قابلیت «جست‌وجوی حساب‌های حرفه‌ای» اینستاگرام (`Business Discovery`) می‌آید که با ورود از طریق اینستاگرام همیشه در دسترس نیست؛ در این صورت پنل آن را صادقانه «پشتیبانی‌نشده» نشان می‌دهد.",
    note_telegram_username_manual: "ربات نمی‌تواند نام کاربری عمومی کانال را تنظیم کند؛ آن را در تنظیمات کانال در تلگرام تغییر دهید.",
    note_telegram_views_public_preview:
      "تلگرام آمار بازدید را به ربات نمی‌دهد؛ بازدیدها از پیش‌نمایش عمومی کانال (`t.me/s`) خوانده می‌شود، مثل خود تلگرام گرد شده است و فقط برای کانال‌های عمومی در دسترس است.",
    settings_title: "هدف‌گذاری صفحه",
    settings_help: "ممیزی نام، بیو، عنوان و متن پست‌ها را با این‌ها می‌سنجد و متن‌های پیشنهادی را بر اساس آن‌ها می‌سازد.",
    keywords: "کلیدواژه‌های هدف",
    keywords_help_IG: "تا ۱۰ عبارت که مخاطب در جست‌وجوی اینستاگرام می‌نویسد؛ هر عبارت دست‌کم دو نویسه.",
    keywords_help_TG: "تا ۱۰ عبارت که مخاطب در جست‌وجوی سراسری تلگرام می‌نویسد؛ هر عبارت دست‌کم دو نویسه.",
    keyword_placeholder: "مثلاً: قهوه‌ی تخصصی",
    keyword_add: "افزودن",
    keyword_remove: "برداشتن {k}",
    keywords_max: "حداکثر ۱۰ کلیدواژه.",
    cta: "دعوت به اقدام",
    cta_placeholder: "مثلاً: سفارش در دایرکت",
    cta_help: "جمله‌ای که ممیزی در بیو یا توضیحات پیشنهاد می‌کند.",
    link: "لینک پیشنهادی",
    link_help: "نشانی سایت یا فروشگاه، با `https://`.",
    link_invalid: "نشانی باید با `https://` یا `http://` شروع شود.",
    timezone: "منطقه‌ی زمانی",
    timezone_help: "برای بهترین ساعت‌های انتشار و تقویم برنامه‌ریز.",
    tz_Asia_Tehran: "تهران",
    tz_Asia_Dubai: "دبی",
    tz_Europe_Istanbul: "استانبول",
    tz_Europe_London: "لندن",
    tz_Europe_Berlin: "برلین",
    tz_America_New_York: "نیویورک",
    tz_America_Toronto: "تورنتو",
    tz_UTC: "زمان هماهنگ جهانی",
    save_settings: "ذخیره‌ی هدف‌گذاری",
    settings_saved: "ذخیره شد. ممیزی بعدی با این هدف‌گذاری انجام می‌شود.",
    next_steps: "قدم‌های بعدی",
    step_audit: "یافته‌های ممیزی و متن‌های پیشنهادی",
    step_analytics: "رشد، تعامل و بهترین زمان انتشار",
    step_planner: "نوشتن و زمان‌بندی پست با تأیید",
    step_competitors: "مقایسه با رقبا",

    // ---------------------------------------------------------------- connect
    connect_title_IG: "اتصال صفحه‌ی اینستاگرام",
    connect_title_TG: "اتصال کانال تلگرام",
    ig_intro:
      "با ورود از طریق خود اینستاگرام، پنل اجازه‌ی خواندن پروفایل، پست‌ها و آمار صفحه و انتشار پست‌هایی را که شما تأیید می‌کنید می‌گیرد. رمز عبور شما هرگز به پنل داده نمی‌شود.",
    ig_req_pro: "حساب باید حرفه‌ای (کسب‌وکار یا تولیدکننده‌ی محتوا) باشد؛ حساب شخصی را در اپ از «تنظیمات ← نوع حساب و ابزارها» تبدیل کنید.",
    ig_perms: "مجوزهایی که درخواست می‌شود",
    perm_basic: "خواندن پروفایل و پست‌ها",
    perm_publish: "انتشار پست‌هایی که یک انسان در پنل تأیید می‌کند",
    perm_insights: "خواندن آمار دسترسی، بازدید و تعامل",
    perm_comments: "خواندن دیدگاه‌ها (برای قابلیت‌های بعدی؛ از الان تا دوباره اجازه لازم نشود)",
    ig_cannot: "پنل نمی‌تواند نام، بیو یا لینک پروفایل را تغییر دهد، چون API اینستاگرام اجازه نمی‌دهد؛ برای این‌ها متن آماده‌ی رونوشت می‌گیرید.",
    ig_connect_btn: "ورود با اینستاگرام و اتصال",
    ig_reconnect_btn: "اتصال دوباره با اینستاگرام",
    ig_nc_title: "اینستاگرام روی این سرور راه‌اندازی نشده است",
    ig_nc_body:
      "برای وصل کردن صفحه‌های اینستاگرام، مدیر سرور باید یک برنامه در پنل توسعه‌دهندگان متا بسازد. تا آن زمان این پروژه هیچ عددی نشان نمی‌دهد؛ چیزی ساختگی جایش نمی‌آید.",
    ig_nc_steps: "مراحل راه‌اندازی، برای مدیر سرور",
    ig_nc_1: "در `developers.facebook.com` یک برنامه از نوع «کسب‌وکار» بسازید.",
    ig_nc_2: "محصول «API اینستاگرام با ورود اینستاگرام» را اضافه کنید و در تنظیمات آن این نشانی بازگشت را ثبت کنید:",
    ig_nc_3: "شناسه و رمز برنامه‌ی اینستاگرام را در متغیرهای `META_APP_ID` و `META_APP_SECRET` سرویس‌های وب و ورکر بگذارید؛ `APP_URL` باید نشانی عمومی پنل با `https://` باشد.",
    ig_nc_4: "سرویس‌ها را دوباره راه‌اندازی و این صفحه را بازآوری کنید.",
    ig_nc_5: "تا متا برنامه را تأیید نکرده، فقط حساب‌هایی وصل می‌شوند که در نقش آزمایش‌کننده به برنامه اضافه شده‌اند.",
    ig_nc_ask: "اگر مدیر سرور نیستید، همین مراحل را برای او بفرستید.",
    ask_admin: "نقش شما اجازه‌ی وصل کردن حساب را ندارد؛ از مدیر سازمان بخواهید.",
    tg_intro:
      "پنل از طریق رباتی کار می‌کند که شما مدیر کانال می‌کنید: تعداد اعضا را می‌خواند، پست‌های تأییدشده را منتشر می‌کند و تغییر عنوان و توضیحات را فقط پس از تأیید شما اعمال می‌کند. ربات به گفتگوهای خصوصی شما دسترسی ندارد.",
    tg_s1: "یک ربات بسازید",
    tg_s1_1: "در تلگرام `@BotFather` را باز کنید و `/newbot` را بفرستید.",
    tg_s1_2: "یک نام و یک نام کاربری که به `bot` ختم شود انتخاب کنید.",
    tg_s1_3: "توکنی را که می‌دهد (شبیه `123456:ABC…`) رونوشت کنید و به هیچ جای دیگری ندهید.",
    tg_s2: "ربات را مدیر کانال کنید",
    tg_s2_1: "در کانال: «مدیریت کانال ← مدیران ← افزودن مدیر»، ربات را جست‌وجو و انتخاب کنید.",
    tg_s2_2: "این سه دسترسی را روشن بگذارید:",
    tg_s2_3: "دسترسی‌های دیگر (حذف پیام، افزودن مدیر و …) لازم نیست؛ خاموش بگذارید.",
    tg_s3: "توکن و کانال را وارد کنید",
    token: "توکن ربات",
    token_help: "فقط برای بررسی و اتصال فرستاده می‌شود، رمزنگاری‌شده نگه داشته می‌شود و دیگر هرگز نمایش داده نمی‌شود.",
    token_format: "توکن شبیه `123456:ABC…` است: عدد، دونقطه و دست‌کم ۳۰ نویسه.",
    channel: "کانال",
    channel_help: "نام کاربری عمومی (مثل `@mychannel` یا `t.me/mychannel`) یا شناسه‌ی عددی کانال خصوصی که با `-100` شروع می‌شود.",
    channel_format: "نام کاربری کانال یا شناسه‌ی عددی آن را وارد کنید.",
    consent:
      "تأیید می‌کنم که مالک یا مدیر این کانال هستم و به پنل اجازه می‌دهم با این ربات آمار کانال را بخواند و فقط پس از تأیید یک انسان پست منتشر کند یا عنوان و توضیحات را تغییر دهد.",
    consent_needed: "برای اتصال، اجازه‌ی بالا را تأیید کنید.",
    tg_connect_btn: "بررسی و اتصال",
    tg_checking: "در حال بررسی دسترسی‌های ربات…",
    tg_connected: "کانال وصل شد. همگام‌سازی و ممیزی اول در جریان است.",
    tg_refused: "اتصال انجام نشد:",
    tg_missing: "این دسترسی‌ها را برای ربات روشن کنید و دوباره تلاش کنید:",
    fs_title: "همگام‌سازی و ممیزی اول",
    fs_running: "پست‌ها، آمار و ممیزی صفحه در حال آماده شدن است؛ معمولاً کمتر از یک دقیقه طول می‌کشد.",
    fs_done: "آماده است. یافته‌های ممیزی و آمار را ببینید.",
    fs_failed: "همگام‌سازی اول ناموفق بود:",

    // ---------------------------------------------------------------- audit
    au_intro_IG:
      "پروفایل و پست‌های ۱۲۰ روز اخیر با قاعده‌های مخصوص اینستاگرام سنجیده می‌شود. API اینستاگرام اجازه‌ی تغییر پروفایل را نمی‌دهد، پس هر پیشنهاد متن آماده‌ی رونوشت دارد.",
    au_intro_TG:
      "عنوان، توضیحات و پست‌های ۱۲۰ روز اخیر با قاعده‌های مخصوص تلگرام سنجیده می‌شود. تغییر عنوان و توضیحات از مسیر اصلاحات و تأیید، با امکان بازگشت، اعمال می‌شود.",
    au_last: "آخرین ممیزی",
    au_filter: "نمایش",
    au_all: "همه",
    au_manual: "در اپ انجام شود",
    au_approval: "با تأیید اعمال می‌شود",
    au_none: "همه‌ی قاعده‌ها قبول شدند؛ یافته‌ای نیست.",
    au_none_filter: "در این دسته یافته‌ای نیست.",
    au_no_run: "هنوز ممیزی اجرا نشده است. پس از هر همگام‌سازی خودکار اجرا می‌شود؛ یا همین حالا اجرا کنید.",
    au_no_data: "هنوز داده‌ای همگام‌سازی نشده؛ بدون پست‌ها، قاعده‌های محتوا و فعالیت چیزی برای سنجیدن ندارند.",
    why: "چرا مهم است",
    suggestion: "پیشنهاد",
    sf_name: "نام",
    sf_bio: "بیو",
    sf_website: "لینک پروفایل",
    sf_title: "عنوان کانال",
    sf_description: "توضیحات کانال",
    sf_username: "نام کاربری",
    sf_alt_text: "متن جایگزین تصویر",
    sf_caption: "کپشن",
    sf_posting: "زمان‌بندی انتشار",
    manual_badge: "در اپ تغییر دهید",
    manual_IG: "API اینستاگرام این را تغییر نمی‌دهد: متن را رونوشت کنید و در اپ اینستاگرام از «ویرایش نمایه» جایگزین کنید.",
    manual_TG: "ربات این را تغییر نمی‌دهد: در تلگرام از تنظیمات کانال ویرایش کنید.",
    approval_badge: "از مسیر تأیید",
    prop_DRAFT: "پیشنهاد اصلاح ساخته شده و منتظر بررسی است.",
    prop_AWAITING_APPROVAL: "در انتظار تأیید یک انسان.",
    prop_APPROVED: "تأیید شده؛ آماده‌ی اعمال.",
    prop_APPLYING: "در حال اعمال…",
    prop_APPLIED: "اعمال شد.",
    prop_FAILED: "اعمال ناموفق بود؛ جزئیات در اصلاحات.",
    prop_REJECTED: "رد شد.",
    prop_ROLLED_BACK: "برگردانده شد.",
    to_fixes: "بررسی در اصلاحات",
    to_approvals: "رفتن به تأییدها",
    no_change_right: "ربات دسترسی «تغییر اطلاعات کانال» ندارد، پس پیشنهادی برای تأیید ساخته نشد. این دسترسی را بدهید و دوباره ممیزی کنید، یا متن را دستی جایگزین کنید.",
    rules_title: "قاعده‌های بررسی‌شده",
    rules_n: "{n} قاعده",
    rules_help: "هر ممیزی همه‌ی این قاعده‌ها را می‌سنجد؛ فرض‌ها در توضیح هر قاعده آمده است.",
    rule_pass: "قبول",
    rule_fail: "یافته",
    cat_profile: "پروفایل",
    cat_content: "محتوا",
    cat_activity: "فعالیت",
    cat_performance: "عملکرد",
    cat_accessibility: "دسترس‌پذیری",
    seen_since: "از {when}",

    // ---------------------------------------------------------------- analytics
    an_intro:
      "فقط آنچه پلتفرم گزارش کرده: روزهای بدون داده خالی می‌ماند و تخمینی جایش نمی‌آید. فرمول هر شاخص پایین صفحه آمده است.",
    range: "بازه",
    range_n: "{n} روز",
    an_followers_IG: "رشد دنبال‌کنندگان",
    an_followers_TG: "رشد اعضا",
    an_net: "تغییر خالص",
    an_no_series: "برای نمودار، دست‌کم دو روز همگام‌سازی لازم است؛ همگام‌سازی روزانه خودکار است.",
    an_daily: "دسترسی، بازدید و تعامل روزانه",
    an_daily_none: "اینستاگرام هنوز آمار روزانه‌ای برای این بازه گزارش نکرده است.",
    reach: "دسترسی",
    views: "بازدید",
    engagement: "تعامل",
    likes: "پسند",
    comments: "دیدگاه",
    saves: "ذخیره",
    shares: "اشتراک",
    interactions: "تعامل‌ها",
    er_reach: "نرخ تعامل (دسترسی)",
    er_followers: "نرخ تعامل (دنبال‌کننده)",
    view_rate: "نرخ بازدید",
    an_posts: "پست‌ها بر اساس نوع",
    an_posts_none: "در این بازه پستی منتشر نشده است.",
    type_image: "تصویر",
    type_video: "ویدیو",
    type_reel: "ریلز",
    type_carousel: "چندتایی",
    type_text: "متن",
    type_photo: "عکس",
    type_album: "آلبوم",
    type_other: "دیگر",
    an_top_IG: "پرتعامل‌ترین پست‌ها",
    an_top_TG: "پربازدیدترین پست‌ها",
    an_best: "بهترین زمان انتشار",
    an_best_help: "میانه‌ی عملکرد پست‌های خود شما در هر ساعت و روز، به وقت {tz}. ساعت یا روزی که کمتر از دو پست دارد نمایش داده نمی‌شود.",
    an_best_none: "برای بهترین زمان، در هر ساعت دست‌کم دو پست با آمار لازم است.",
    an_hours: "ساعت‌های روز",
    an_days: "روزهای هفته",
    an_bucket: "{label}: میانه {v} از {n} پست",
    an_top_bucket: "بهترین",
    an_hashtags: "عملکرد هشتگ‌ها",
    an_hashtags_none: "هیچ هشتگی دست‌کم در دو پست این بازه نیامده است.",
    col_tag: "هشتگ",
    col_posts: "پست",
    col_avg: "میانگین",
    col_lift: "اثر",
    lift_help: "اثر ۱٫۲ یعنی پست‌های دارای این هشتگ ۲۰٪ بهتر از میانگین همه‌ی پست‌ها بوده‌اند.",
    lift_fmt: "{n} برابر",
    an_formulas: "فرمول‌ها",
    f_erByReach: "نرخ تعامل بر پایه‌ی دسترسی",
    f_erByFollowers: "نرخ تعامل بر پایه‌ی دنبال‌کننده",
    f_viewRate: "نرخ بازدید",
    f_bestTimes: "بهترین زمان",
    f_hashtagLift: "اثر هشتگ",
    wd_0: "یکشنبه",
    wd_1: "دوشنبه",
    wd_2: "سه‌شنبه",
    wd_3: "چهارشنبه",
    wd_4: "پنجشنبه",
    wd_5: "جمعه",
    wd_6: "شنبه",
    hour_fmt: "ساعت {h}",

    // ---------------------------------------------------------------- posts
    po_intro: "پست‌های همگام‌شده با آمار هرکدام و منبع آن. آمار پست‌های کمتر از دو روز هنوز در حال رشد است.",
    sort: "مرتب‌سازی",
    sort_recent: "تازه‌ترین",
    sort_top: "برترین",
    col_date: "زمان انتشار",
    col_type: "نوع",
    col_text: "متن",
    col_metrics: "آمار",
    col_source: "منبع",
    open_post: "باز کردن پست",
    po_empty: "هنوز پستی همگام‌سازی نشده است.",
    no_caption: "بدون متن",
    page_of: "صفحه‌ی {p} از {n}",
    prev: "قبلی",
    next: "بعدی",
    total_posts: "{n} پست",

    // ---------------------------------------------------------------- competitors
    co_intro_IG: "حساب‌های حرفه‌ای رقیب را اضافه کنید تا دنبال‌کننده، تعداد انتشار و تعامل‌شان کنار صفحه‌ی شما بیاید.",
    co_intro_TG: "کانال‌های عمومی رقیب را اضافه کنید تا اعضا، تعداد انتشار و بازدیدشان کنار کانال شما بیاید. آمار از پیش‌نمایش عمومی تلگرام خوانده می‌شود.",
    co_add_label: "رقیب تازه",
    co_placeholder: "نام کاربری یا نشانی صفحه",
    co_add: "افزودن رقیب",
    co_added: "اضافه شد؛ آمارش در حال خوانده شدن است.",
    co_refresh_all: "به‌روزرسانی همه",
    co_refresh: "به‌روزرسانی",
    co_refreshed: "آمار رقبا به‌روز شد.",
    co_remove: "حذف",
    co_limit: "حداکثر {n} رقیب.",
    co_empty: "هنوز رقیبی اضافه نشده است.",
    co_invalid: "یک نام کاربری معتبر (۲ تا ۳۲ حرف انگلیسی، عدد، نقطه یا زیرخط) یا نشانی صفحه وارد کنید.",
    co_duplicate: "این رقیب از قبل اضافه شده است.",
    col_account: "حساب",
    col_status: "وضعیت",
    col_followers_IG: "دنبال‌کننده",
    col_followers_TG: "عضو",
    col_ppw: "پست در هفته",
    col_avg_views: "میانگین بازدید",
    col_avg_int: "میانگین تعامل",
    col_fetched: "آخرین بررسی",
    cs_ok: "به‌روز",
    cs_pending: "در انتظار اولین بررسی",
    cs_unsupported: "پشتیبانی‌نشده",
    cs_not_found: "پیدا نشد",
    cs_no_public_preview: "خصوصی",
    cs_error: "خطا",
    co_compare: "مقایسه با شما",
    you: "شما",
    co_unsupported_title: "آمار رقبای اینستاگرام با این اتصال در دسترس نیست",
    co_unsupported_body:
      "اینستاگرام آمار حساب‌های دیگر را فقط از طریق «جست‌وجوی حساب‌های حرفه‌ای» می‌دهد که برای این اتصال فعال نیست. رقبا فهرست می‌شوند اما عددی برایشان ساخته نمی‌شود.",
    co_unknown_bd: "در دسترس بودن آمار رقبای اینستاگرام در اولین به‌روزرسانی مشخص می‌شود.",
    co_source: "منبع آمار",
    co_recent: "{n} پست اخیر دیده شد",

    // ---------------------------------------------------------------- planner
    pl_intro: "هیچ پستی بدون تأیید یک انسان با نقش تأییدکننده منتشر نمی‌شود. زمان‌ها به وقت {tz} است.",
    new_post: "پست تازه",
    view_list: "فهرست",
    view_month: "ماه",
    view_week: "هفته",
    prev_period: "قبلی",
    next_period: "بعدی",
    today: "امروز",
    f_all: "همه",
    f_awaiting: "در انتظار تأیید",
    f_scheduled: "زمان‌بندی‌شده",
    f_draft: "پیش‌نویس",
    f_published: "منتشرشده",
    f_failed: "ناموفق",
    f_closed: "ردشده و لغوشده",
    ps_draft: "پیش‌نویس",
    ps_awaiting_approval: "در انتظار تأیید",
    ps_rejected: "رد شده",
    ps_scheduled: "زمان‌بندی‌شده",
    ps_publishing: "در حال انتشار",
    ps_published: "منتشر شد",
    ps_failed: "ناموفق",
    ps_canceled: "لغو شده",
    pl_empty: "در این دسته پستی نیست.",
    pl_empty_all: "هنوز پستی برنامه‌ریزی نشده است. اولین پست را بنویسید؛ پس از تأیید در زمان خودش منتشر می‌شود.",
    op: "نوع کار",
    op_post: "پست تازه",
    op_edit: "ویرایش پیام منتشرشده",
    op_pin: "سنجاق کردن پیام",
    format: "قالب",
    fmt_image: "تصویر",
    fmt_carousel: "چندتایی",
    fmt_reel: "ریلز",
    fmt_text: "متن",
    fmt_photo: "عکس",
    fmt_album: "آلبوم",
    fmt_video: "ویدیو",
    c_new: "پست تازه",
    c_edit: "ویرایش پست برنامه‌ریزی‌شده",
    c_copy: "نسخه‌ی تازه از پست",
    c_text_TG: "متن",
    c_text_help_TG: "قالب‌بندی تلگرام: پررنگ، کج، زیرخط، پیوند و … با دکمه‌های بالا. برچسب‌های دیگر پذیرفته نمی‌شود.",
    c_caption: "کپشن",
    c_caption_help: "کلیدواژه‌ی هدف را در خط اول بیاورید؛ اینستاگرام ۳ تا ۵ هشتگ مرتبط را توصیه می‌کند.",
    c_counter: "{n} از {max} نویسه",
    c_hashtags: "{n} از {max} هشتگ",
    c_media: "رسانه",
    c_media_help_IG: "نشانی `https://` که اینستاگرام بتواند دانلود کند؛ تصویرها باید `JPEG` باشند. پنل فایل را دانلود یا نمایش نمی‌دهد.",
    c_media_help_TG: "نشانی عمومی `https://` عکس یا ویدیو؛ تلگرام خودش آن را دریافت می‌کند.",
    c_media_url: "نشانی رسانه {n}",
    c_media_type: "نوع",
    media_image: "تصویر",
    media_video: "ویدیو",
    c_alt: "متن جایگزین",
    c_alt_help: "توصیف تصویر برای نابینایان و برای درک محتوا توسط اینستاگرام.",
    c_add_media: "افزودن رسانه",
    c_remove_media: "برداشتن رسانه {n}",
    c_pin: "پس از ارسال سنجاق شود",
    c_silent: "بی‌صدا ارسال شود (بدون اعلان برای اعضا)",
    c_share_feed: "در صفحه‌ی اصلی پست‌ها هم نمایش داده شود",
    c_message_id: "شماره‌ی پیام",
    c_message_id_help: "عدد آخر نشانی پیام، مثلاً ۱۲۳ در `t.me/channel/123`.",
    c_target: "بخش ویرایش‌شونده",
    target_text: "متن پیام",
    target_caption: "کپشن رسانه",
    c_new_text: "متن تازه",
    c_when: "زمان انتشار",
    when_asap: "بلافاصله پس از تأیید",
    when_at: "در زمان مشخص",
    c_when_tz: "به وقت {tz}",
    c_when_past: "این زمان گذشته است؛ پس از تأیید بلافاصله منتشر می‌شود.",
    c_preview: "پیش‌نمایش",
    c_preview_media: "{n} رسانه",
    c_preview_empty: "متنی نوشته نشده است.",
    c_preview_note: "پیش‌نمایش تقریبی است؛ رسانه‌ها نمایش داده نمی‌شوند.",
    c_save_draft: "ذخیره‌ی پیش‌نویس",
    c_submit: "ذخیره و ارسال برای تأیید",
    c_saved: "پیش‌نویس ذخیره شد.",
    c_submitted: "برای تأیید فرستاده شد.",
    c_edit_note: "ویرایش، درخواست تأیید قبلی را پس می‌گیرد؛ آنچه تأیید می‌شود همان است که منتشر می‌شود.",
    c_problems: "پیش از ذخیره این‌ها را درست کنید:",
    tb_label: "قالب‌بندی متن",
    tb_bold: "پررنگ",
    tb_italic: "کج",
    tb_underline: "زیرخط",
    tb_strike: "خط‌خورده",
    tb_link: "پیوند",
    tb_code: "کد",
    tb_spoiler: "پنهان",
    tb_quote: "نقل‌قول",
    link_prompt: "نشانی پیوند",
    link_insert: "درج پیوند",
    pr_caption_too_long: "متن بیش از {n} نویسه است.",
    pr_too_many_hashtags: "بیش از {n} هشتگ.",
    pr_image_needs_one_image: "قالب تصویر دقیقاً یک تصویر لازم دارد.",
    pr_reel_needs_one_video: "ریلز دقیقاً یک ویدیو لازم دارد.",
    pr_carousel_needs_2_to_10_items: "چندتایی ۲ تا ۱۰ رسانه لازم دارد.",
    pr_instagram_images_must_be_jpeg: "تصویرهای اینستاگرام باید `JPEG` باشند (نشانی به `.jpg` یا `.jpeg` ختم شود).",
    pr_format_not_for_instagram: "این قالب برای اینستاگرام نیست.",
    pr_instagram_supports_new_posts_only: "در اینستاگرام فقط پست تازه ممکن است.",
    pr_text_required: "متن پیام خالی است.",
    pr_text_too_long: "متن بیش از حد مجاز تلگرام است.",
    pr_text_post_has_no_media: "پست متنی رسانه ندارد؛ قالب را عکس، آلبوم یا ویدیو کنید.",
    pr_photo_needs_one_image: "قالب عکس دقیقاً یک تصویر لازم دارد.",
    pr_video_needs_one_video: "قالب ویدیو دقیقاً یک ویدیو لازم دارد.",
    pr_album_needs_2_to_10_items: "آلبوم ۲ تا ۱۰ رسانه لازم دارد.",
    pr_format_not_for_telegram: "این قالب برای تلگرام نیست.",
    pr_tag_not_allowed: "تلگرام این برچسب را نمی‌پذیرد: `{tag}`",
    pr_span_needs_tg_spoiler: "برچسب `span` فقط برای متن پنهان پذیرفته است.",
    pr_link_needs_href: "پیوند نشانی `https://` ندارد.",
    pr_unbalanced: "برچسب `{tag}` درست بسته نشده است.",
    pr_unclosed: "برچسب باز مانده: `{tag}`",
    pr_bare_lt: "نویسه‌ی «<» تنها پذیرفته نیست؛ به‌جایش `&lt;` بنویسید.",
    pr_bare_ampersand: "نویسه‌ی «&» تنها پذیرفته نیست؛ به‌جایش `&amp;` بنویسید.",
    pr_media_https: "نشانی رسانه {n} باید با `https://` شروع شود.",
    pr_message_id: "شماره‌ی پیام را وارد کنید.",
    pr_unknown: "مشکل: {code}",
    a_edit: "ویرایش",
    a_submit: "ارسال برای تأیید",
    a_approve: "تأیید انتشار",
    a_reject: "رد",
    a_reject_reason: "دلیل رد (اختیاری)",
    a_reject_confirm: "رد شود",
    a_publish_now: "انتشار همین حالا",
    a_retry: "تلاش دوباره",
    a_cancel: "لغو",
    a_cancel_confirm: "لغو شود؟",
    a_open: "دیدن پست",
    a_copy: "ساخت نسخه‌ی تازه",
    m_approved: "تأیید شد؛ در زمان خودش منتشر می‌شود.",
    m_rejected: "رد شد.",
    m_publishing: "در صف انتشار است…",
    m_published: "منتشر شد.",
    m_canceled: "لغو شد.",
    m_submitted: "برای تأیید فرستاده شد.",
    m_failed: "انتشار ناموفق بود:",
    approver_only: "تأیید، رد و انتشار فوری فقط با نقش تأییدکننده ممکن است.",
    requested: "درخواست تأیید: {when}",
    decided: "تصمیم: {when}",
    decision_reason: "دلیل: {r}",
    attempts: "{n} تلاش",
    publish_at: "انتشار: {when}",
    publish_asap: "انتشار: بلافاصله پس از تأیید",
    published_at: "منتشر شد: {when}",
    fail_reason: "دلیل:",
    ou_title: "معلوم نیست منتشر شد یا نه",
    ou_body:
      "ارتباط وسط انتشار قطع شد. برای جلوگیری از پست تکراری، پنل دوباره ارسال نمی‌کند. کانال یا صفحه را نگاه کنید: اگر پست منتشر نشده، از همین‌جا نسخه‌ی تازه بسازید.",
    retry_note: "تا سه بار با فاصله خودکار تلاش می‌شود؛ پس از آن با «تلاش دوباره» دستی منتشر کنید.",
    op_edit_label: "ویرایش پیام {id}",
    op_pin_label: "سنجاق پیام {id}",
    cal_more: "{n} مورد دیگر",
    cal_none: "در این بازه پستی زمان‌بندی نشده است.",

    // ---------------------------------------------------------------- dashboard / onboarding
    db_upcoming: "انتشارهای پیش رو",
    db_upcoming_none: "پستی در صف انتشار نیست.",
    db_awaiting: "{n} پست در انتظار تأیید",
    db_top_findings: "مهم‌ترین یافته‌ها",
    db_open_planner: "برنامه‌ریز",
    db_open_audit: "همه‌ی یافته‌ها",
    db_open_analytics: "آمار کامل",
    ob_type: "نوع پروژه",
    ob_WEBSITE: "وب‌سایت",
    ob_WEBSITE_desc: "خزش و ممیزی فنی سایت، کلمات کلیدی و سرعت، اتصال وردپرس یا Cloudflare و اعمال اصلاحات با تأیید.",
    ob_INSTAGRAM: "صفحه‌ی اینستاگرام",
    ob_INSTAGRAM_desc: "ممیزی نام، بیو و کپشن‌ها برای جست‌وجوی اینستاگرام، آمار تعامل، بهترین زمان انتشار، رقبا و انتشار زمان‌بندی‌شده با تأیید.",
    ob_TELEGRAM: "کانال تلگرام",
    ob_TELEGRAM_desc: "ممیزی عنوان و توضیحات برای جست‌وجوی تلگرام، نرخ بازدید، رقبا و انتشار زمان‌بندی‌شده با تأیید، از طریق ربات مدیر کانال.",
    ob_handle_IG: "نام کاربری صفحه (اختیاری)",
    ob_handle_TG: "نام کاربری کانال (اختیاری)",
    ob_handle_help: "فقط برای نمایش تا وقتی حساب وصل شود؛ پس از اتصال، نام واقعی جایش می‌نشیند.",
    ob_handle_invalid: "نام کاربری ۲ تا ۳۲ حرف انگلیسی، عدد، نقطه یا زیرخط است.",
    ob_s1: "ساخت پروژه",
    ob_s2: "اتصال حساب",
    ob_s3: "همگام‌سازی اول",
    ob_s4: "ممیزی و پیشنهادها",
    ob_done: "همه چیز آماده است.",
    ob_open: "رفتن به صفحه",
    ob_lock: "هیچ پستی بدون تأیید یک انسان منتشر نمی‌شود و تغییر عنوان و توضیحات کانال هم فقط پس از تأیید اعمال می‌شود؛ این قاعده در سرور و دیتابیس اعمال می‌شود، نه فقط در رابط کاربری.",
  },
  {
    platform_INSTAGRAM: "Instagram",
    platform_TELEGRAM: "Telegram",
    page_IG: "Instagram page",
    page_TG: "Telegram channel",
    st_CONNECTED: "Connected",
    st_NOT_CONNECTED: "Not connected",
    st_ERROR: "Connection error",
    src_api_IG: "Instagram API",
    src_api_TG: "Telegram Bot API",
    src_public_preview: "Telegram public preview",
    src_business_discovery: "Instagram Business Discovery",
    src_help_api_IG: "Reported by Instagram itself, with the page owner's authorization.",
    src_help_api_TG: "Reported by Telegram itself to the channel's admin bot.",
    src_help_public_preview: "Read from the channel's public page and rounded the way Telegram rounds it (e.g. 1.2K).",
    not_connected_title_IG: "The Instagram page is not connected yet",
    not_connected_title_TG: "The Telegram channel is not connected yet",
    not_connected_body: "Nothing is shown until the account is connected. You connect once; after that a daily sync runs by itself.",
    go_connect: "Go to connect",
    no_social_project: "This screen is for Instagram and Telegram projects.",
    sev_CRITICAL: "Critical",
    sev_SERIOUS: "Serious",
    sev_WARNING: "Warning",
    sev_INFO: "Info",
    followers_IG: "followers",
    followers_TG: "members",
    unknown_reason: "An unrecognised error from the platform.",
    open_on_platform_IG: "Open in Instagram",
    open_on_platform_TG: "Open in Telegram",
    no_permission: "Your role does not allow that.",

    ov_intro_IG:
      "The Instagram page at a glance: connection, audit score, key metrics and targeting. Every number is what Instagram reported; nothing is estimated.",
    ov_intro_TG:
      "The Telegram channel at a glance: the bot's connection, audit score, key metrics and targeting. Member counts come from the bot, views from Telegram's public preview.",
    ig_connected: "Instagram is connected. The first sync is running.",
    ig_failed: "Instagram could not be connected:",
    sync_now: "Sync",
    syncing: "Syncing…",
    sync_done: "Sync finished; the data is fresh.",
    sync_failed: "The sync failed:",
    sync_slow: "The sync is still running; the result shows here when it finishes.",
    check: "Check connection",
    check_ok: "The connection is healthy and its rights were refreshed.",
    check_failed: "Connection check:",
    disconnect: "Disconnect",
    disconnect_confirm: "Disconnect?",
    disconnected: "Disconnected: the token was deleted; history, audits and plans were kept.",
    disconnect_help: "The page or channel is not touched; the panel simply loses access to it.",
    last_sync: "Last sync",
    never: "Not yet",
    connected_at: "Connected since",
    token_expires: "Connection valid until",
    token_renew_help: "Each sync renews the connection before it expires.",
    account_type: "Account type",
    acct_BUSINESS: "Business",
    acct_MEDIA_CREATOR: "Creator",
    updates_mode: "New posts arrive",
    mode_webhook: "Instantly",
    mode_polling: "On each sync",
    webhook_failed: "Instant delivery could not be registered; new posts are read on the next sync.",
    bot: "Admin bot",
    rights: "Bot rights",
    right_can_post_messages: "Post messages",
    right_can_edit_messages: "Edit messages of others",
    right_can_change_info: "Change channel info",
    right_can_pin_messages: "Pin messages",
    right_use_can_post_messages: "publishes planned posts",
    right_use_can_edit_messages: "edits and pins posts",
    right_use_can_change_info: "applies suggested titles and descriptions, after your approval",
    right_missing: "Missing",
    right_ok: "Granted",
    no_bio: "No description",
    website: "Link",
    score: "Profile score",
    score_help: "100 minus a weight per finding by severity: critical 20, serious 12, warning 6, info 2.",
    no_audit: "No audit has run yet.",
    run_audit: "Audit now",
    auditing: "Auditing…",
    audit_done: "Audit finished: score {score}, {n} findings.",
    findings_n: "{n} findings",
    view_findings: "See the findings",
    metrics: "Last 28 days",
    m_followers_IG: "Followers",
    m_followers_TG: "Members",
    m_change: "{n} in this range",
    m_change_pct: "{n}%",
    m_posts_week: "Posts per week",
    m_posts_n: "{n} posts in this range",
    m_er_reach: "Engagement rate by reach",
    m_er_followers: "Engagement rate by followers",
    m_avg_views: "Average views per post",
    m_view_rate: "View rate",
    m_no_data: "No data",
    m_no_change: "A change needs at least two days of data",
    caps_title: "What this connection can do",
    cap_edit_profile_IG: "Edit the profile's name, bio and link",
    cap_edit_profile_TG: "Change the channel title and description (after approval)",
    cap_publish: "Publish posts",
    cap_edit_posts: "Edit published posts",
    cap_pin: "Pin a message",
    cap_competitors: "Competitor figures",
    cap_views_TG: "Post view counts",
    cap_yes: "Yes",
    cap_no: "No",
    cap_unknown: "Not known yet",
    note_instagram_profile_manual:
      "The Instagram API cannot edit the profile's name, bio or link; the panel prepares the suggested text and you paste it in the app.",
    note_instagram_competitors_business_discovery:
      "Competitor figures come from Instagram's `Business Discovery`, which is not always available with Instagram Login; when it is not, the panel says \"unsupported\" instead of guessing.",
    note_telegram_username_manual: "A bot cannot set the channel's public username; change it in the channel's settings in Telegram.",
    note_telegram_views_public_preview:
      "Telegram does not give view counts to bots; views are read from the channel's public preview (`t.me/s`), rounded as Telegram shows them, and exist for public channels only.",
    settings_title: "Targeting",
    settings_help: "The audit judges the name, bio, title and post texts against these and builds its suggested texts from them.",
    keywords: "Target keywords",
    keywords_help_IG: "Up to 10 phrases people type into Instagram search; at least two characters each.",
    keywords_help_TG: "Up to 10 phrases people type into Telegram's global search; at least two characters each.",
    keyword_placeholder: "e.g. specialty coffee",
    keyword_add: "Add",
    keyword_remove: "Remove {k}",
    keywords_max: "At most 10 keywords.",
    cta: "Call to action",
    cta_placeholder: "e.g. Order via DM",
    cta_help: "The sentence the audit suggests for the bio or description.",
    link: "Suggested link",
    link_help: "The site or shop address, with https.",
    link_invalid: "The address must start with https:// or http://.",
    timezone: "Time zone",
    timezone_help: "For the best publishing hours and the planner's calendar.",
    tz_Asia_Tehran: "Tehran",
    tz_Asia_Dubai: "Dubai",
    tz_Europe_Istanbul: "Istanbul",
    tz_Europe_London: "London",
    tz_Europe_Berlin: "Berlin",
    tz_America_New_York: "New York",
    tz_America_Toronto: "Toronto",
    tz_UTC: "Coordinated Universal Time",
    save_settings: "Save targeting",
    settings_saved: "Saved. The next audit uses this targeting.",
    next_steps: "Next steps",
    step_audit: "Audit findings and suggested texts",
    step_analytics: "Growth, engagement and the best time to post",
    step_planner: "Write and schedule posts with approval",
    step_competitors: "Compare with competitors",

    connect_title_IG: "Connect the Instagram page",
    connect_title_TG: "Connect the Telegram channel",
    ig_intro:
      "Signing in through Instagram itself gives the panel permission to read the profile, posts and statistics, and to publish the posts you approve. Your password is never given to the panel.",
    ig_req_pro: "The account must be professional (Business or Creator); switch a personal account in the app under Settings → Account type and tools.",
    ig_perms: "Permissions requested",
    perm_basic: "Read the profile and posts",
    perm_publish: "Publish posts a person approved in the panel",
    perm_insights: "Read reach, views and engagement statistics",
    perm_comments: "Read comments (for upcoming features; asked now so no second consent is needed)",
    ig_cannot: "The panel cannot change the profile's name, bio or link, because the Instagram API does not allow it; for those you get text ready to copy.",
    ig_connect_btn: "Sign in with Instagram and connect",
    ig_reconnect_btn: "Reconnect with Instagram",
    ig_nc_title: "Instagram is not set up on this server",
    ig_nc_body:
      "To connect Instagram pages, the server's administrator must create an app in Meta's developer console. Until then this project shows no numbers; nothing made up takes their place.",
    ig_nc_steps: "Setup steps, for the server administrator",
    ig_nc_1: "At `developers.facebook.com`, create an app of type Business.",
    ig_nc_2: "Add the product \"Instagram API with Instagram Login\" and register this redirect address in its settings:",
    ig_nc_3: "Put the Instagram app ID and secret in `META_APP_ID` and `META_APP_SECRET` on the web and worker services; `APP_URL` must be the panel's public https address.",
    ig_nc_4: "Restart the services and reload this page.",
    ig_nc_5: "Until Meta reviews the app, only accounts added to it as testers can connect.",
    ig_nc_ask: "If you do not run the server, send these steps to whoever does.",
    ask_admin: "Your role cannot connect accounts; ask an organization admin.",
    tg_intro:
      "The panel works through a bot you make an administrator of the channel: it reads the member count, publishes approved posts and applies title and description changes only after your approval. The bot has no access to your private chats.",
    tg_s1: "Create a bot",
    tg_s1_1: "In Telegram, open `@BotFather` and send `/newbot`.",
    tg_s1_2: "Choose a name and a username ending in `bot`.",
    tg_s1_3: "Copy the token it gives you (like `123456:ABC…`) and do not share it anywhere else.",
    tg_s2: "Make the bot a channel administrator",
    tg_s2_1: "In the channel: Manage channel → Administrators → Add admin, then search for the bot and pick it.",
    tg_s2_2: "Leave these three rights on:",
    tg_s2_3: "No other right (delete messages, add admins, …) is needed; leave them off.",
    tg_s3: "Enter the token and the channel",
    token: "Bot token",
    token_help: "Sent only to check and connect, stored encrypted and never shown again.",
    token_format: "A token looks like `123456:ABC…`: digits, a colon and at least 30 characters.",
    channel: "Channel",
    channel_help: "The public username (like `@mychannel` or `t.me/mychannel`) or a private channel's numeric id, which starts with `-100`.",
    channel_format: "Enter the channel's username or its numeric id.",
    consent:
      "I confirm I own or manage this channel and allow the panel to read its statistics through this bot, and to publish posts or change the title and description only after a person approves.",
    consent_needed: "To connect, confirm the permission above.",
    tg_connect_btn: "Check and connect",
    tg_checking: "Checking the bot's rights…",
    tg_connected: "The channel is connected. The first sync and audit are running.",
    tg_refused: "Could not connect:",
    tg_missing: "Turn these rights on for the bot and try again:",
    fs_title: "First sync and audit",
    fs_running: "Posts, statistics and the profile audit are being prepared; it usually takes less than a minute.",
    fs_done: "Ready. See the audit findings and the statistics.",
    fs_failed: "The first sync failed:",

    au_intro_IG:
      "The profile and the last 120 days of posts are checked against Instagram-specific rules. The Instagram API cannot change the profile, so every suggestion comes with text ready to copy.",
    au_intro_TG:
      "The title, description and the last 120 days of posts are checked against Telegram-specific rules. Title and description changes go through fixes and approval, and can be rolled back.",
    au_last: "Last audit",
    au_filter: "Show",
    au_all: "All",
    au_manual: "Done in the app",
    au_approval: "Applied after approval",
    au_none: "Every rule passes; there are no findings.",
    au_none_filter: "No findings in this group.",
    au_no_run: "No audit has run yet. It runs after every sync; or run it now.",
    au_no_data: "Nothing has been synced yet; without posts the content and activity rules have nothing to judge.",
    why: "Why it matters",
    suggestion: "Suggestion",
    sf_name: "Name",
    sf_bio: "Bio",
    sf_website: "Profile link",
    sf_title: "Channel title",
    sf_description: "Channel description",
    sf_username: "Username",
    sf_alt_text: "Image alt text",
    sf_caption: "Caption",
    sf_posting: "Publishing schedule",
    manual_badge: "Change it in the app",
    manual_IG: "The Instagram API cannot change this: copy the text and paste it in the Instagram app under Edit profile.",
    manual_TG: "The bot cannot change this: edit it in the channel's settings in Telegram.",
    approval_badge: "Through approval",
    prop_DRAFT: "A fix proposal was created and waits for review.",
    prop_AWAITING_APPROVAL: "Waiting for a person's approval.",
    prop_APPROVED: "Approved; ready to apply.",
    prop_APPLYING: "Applying…",
    prop_APPLIED: "Applied.",
    prop_FAILED: "Applying failed; details in Fixes.",
    prop_REJECTED: "Rejected.",
    prop_ROLLED_BACK: "Rolled back.",
    to_fixes: "Review in Fixes",
    to_approvals: "Go to Approvals",
    no_change_right: "The bot lacks the Change channel info right, so no proposal was created for approval. Grant it and audit again, or replace the text by hand.",
    rules_title: "Rules checked",
    rules_n: "{n} rules",
    rules_help: "Every audit checks all of these; each rule states its assumptions.",
    rule_pass: "Pass",
    rule_fail: "Finding",
    cat_profile: "Profile",
    cat_content: "Content",
    cat_activity: "Activity",
    cat_performance: "Performance",
    cat_accessibility: "Accessibility",
    seen_since: "since {when}",

    an_intro: "Only what the platform reported: days without data stay empty and nothing is estimated. Each metric's formula is at the bottom.",
    range: "Range",
    range_n: "{n} days",
    an_followers_IG: "Follower growth",
    an_followers_TG: "Member growth",
    an_net: "Net change",
    an_no_series: "The chart needs at least two days of syncs; the daily sync runs by itself.",
    an_daily: "Daily reach, views and engagement",
    an_daily_none: "Instagram has not reported daily figures for this range yet.",
    reach: "Reach",
    views: "Views",
    engagement: "Engagement",
    likes: "Likes",
    comments: "Comments",
    saves: "Saves",
    shares: "Shares",
    interactions: "Interactions",
    er_reach: "ER (reach)",
    er_followers: "ER (followers)",
    view_rate: "View rate",
    an_posts: "Posts by type",
    an_posts_none: "No posts were published in this range.",
    type_image: "Image",
    type_video: "Video",
    type_reel: "Reel",
    type_carousel: "Carousel",
    type_text: "Text",
    type_photo: "Photo",
    type_album: "Album",
    type_other: "Other",
    an_top_IG: "Most engaging posts",
    an_top_TG: "Most viewed posts",
    an_best: "Best time to post",
    an_best_help: "The median performance of your own posts per hour and weekday, in {tz}. Hours or days with fewer than two posts are not shown.",
    an_best_none: "The best time needs at least two posts with figures per hour.",
    an_hours: "Hours of the day",
    an_days: "Days of the week",
    an_bucket: "{label}: median {v} from {n} posts",
    an_top_bucket: "Best",
    an_hashtags: "Hashtag performance",
    an_hashtags_none: "No hashtag appears in at least two posts in this range.",
    col_tag: "Hashtag",
    col_posts: "Posts",
    col_avg: "Average",
    col_lift: "Lift",
    lift_help: "A lift of 1.2 means posts with this hashtag did 20% better than the average of all posts.",
    lift_fmt: "{n}×",
    an_formulas: "Formulas",
    f_erByReach: "Engagement rate by reach",
    f_erByFollowers: "Engagement rate by followers",
    f_viewRate: "View rate",
    f_bestTimes: "Best time",
    f_hashtagLift: "Hashtag lift",
    wd_0: "Sunday",
    wd_1: "Monday",
    wd_2: "Tuesday",
    wd_3: "Wednesday",
    wd_4: "Thursday",
    wd_5: "Friday",
    wd_6: "Saturday",
    hour_fmt: "{h}:00",

    po_intro: "Synced posts with their figures and where each came from. Figures of posts under two days old are still growing.",
    sort: "Sort",
    sort_recent: "Newest",
    sort_top: "Top",
    col_date: "Published",
    col_type: "Type",
    col_text: "Text",
    col_metrics: "Figures",
    col_source: "Source",
    open_post: "Open the post",
    po_empty: "No posts have been synced yet.",
    no_caption: "No text",
    page_of: "Page {p} of {n}",
    prev: "Previous",
    next: "Next",
    total_posts: "{n} posts",

    co_intro_IG: "Add competing professional accounts to see their followers, posting frequency and engagement next to your page.",
    co_intro_TG: "Add competing public channels to see their members, posting frequency and views next to your channel. Figures are read from Telegram's public preview.",
    co_add_label: "New competitor",
    co_placeholder: "Username or profile address",
    co_add: "Add competitor",
    co_added: "Added; its figures are being read.",
    co_refresh_all: "Refresh all",
    co_refresh: "Refresh",
    co_refreshed: "Competitor figures refreshed.",
    co_remove: "Remove",
    co_limit: "At most {n} competitors.",
    co_empty: "No competitor has been added yet.",
    co_invalid: "Enter a valid username (2–32 letters, digits, dots or underscores) or a profile address.",
    co_duplicate: "This competitor is already tracked.",
    col_account: "Account",
    col_status: "Status",
    col_followers_IG: "Followers",
    col_followers_TG: "Members",
    col_ppw: "Posts / week",
    col_avg_views: "Avg. views",
    col_avg_int: "Avg. interactions",
    col_fetched: "Last checked",
    cs_ok: "Up to date",
    cs_pending: "Waiting for the first check",
    cs_unsupported: "Unsupported",
    cs_not_found: "Not found",
    cs_no_public_preview: "Private",
    cs_error: "Error",
    co_compare: "Compared with you",
    you: "You",
    co_unsupported_title: "Instagram competitor figures are not available with this connection",
    co_unsupported_body:
      "Instagram gives other accounts' figures only through Business Discovery, which this connection cannot use. Competitors are listed, but no numbers are made up for them.",
    co_unknown_bd: "Whether Instagram competitor figures are available is found out on the first refresh.",
    co_source: "Source",
    co_recent: "{n} recent posts seen",

    pl_intro: "No post is published without the approval of a person with the approver role. Times are in {tz}.",
    new_post: "New post",
    view_list: "List",
    view_month: "Month",
    view_week: "Week",
    prev_period: "Previous",
    next_period: "Next",
    today: "Today",
    f_all: "All",
    f_awaiting: "Awaiting approval",
    f_scheduled: "Scheduled",
    f_draft: "Drafts",
    f_published: "Published",
    f_failed: "Failed",
    f_closed: "Rejected & canceled",
    ps_draft: "Draft",
    ps_awaiting_approval: "Awaiting approval",
    ps_rejected: "Rejected",
    ps_scheduled: "Scheduled",
    ps_publishing: "Publishing",
    ps_published: "Published",
    ps_failed: "Failed",
    ps_canceled: "Canceled",
    pl_empty: "No posts in this group.",
    pl_empty_all: "Nothing is planned yet. Write the first post; once approved it is published at its time.",
    op: "Action",
    op_post: "New post",
    op_edit: "Edit a published message",
    op_pin: "Pin a message",
    format: "Format",
    fmt_image: "Image",
    fmt_carousel: "Carousel",
    fmt_reel: "Reel",
    fmt_text: "Text",
    fmt_photo: "Photo",
    fmt_album: "Album",
    fmt_video: "Video",
    c_new: "New post",
    c_edit: "Edit planned post",
    c_copy: "New copy of a post",
    c_text_TG: "Text",
    c_text_help_TG: "Telegram formatting: bold, italic, underline, links and more with the buttons above. Other tags are not accepted.",
    c_caption: "Caption",
    c_caption_help: "Put the target keyword in the first line; Instagram recommends 3–5 relevant hashtags.",
    c_counter: "{n} of {max} characters",
    c_hashtags: "{n} of {max} hashtags",
    c_media: "Media",
    c_media_help_IG: "An https address Instagram can download; images must be JPEG. The panel does not download or display the file.",
    c_media_help_TG: "A public https address of a photo or video; Telegram fetches it itself.",
    c_media_url: "Media address {n}",
    c_media_type: "Type",
    media_image: "Image",
    media_video: "Video",
    c_alt: "Alt text",
    c_alt_help: "Describes the image for blind visitors and helps Instagram understand it.",
    c_add_media: "Add media",
    c_remove_media: "Remove media {n}",
    c_pin: "Pin after sending",
    c_silent: "Send silently (no notification for members)",
    c_share_feed: "Also show it on the profile grid",
    c_message_id: "Message number",
    c_message_id_help: "The last number in the message's address, e.g. 123 in `t.me/channel/123`.",
    c_target: "Part to edit",
    target_text: "Message text",
    target_caption: "Media caption",
    c_new_text: "New text",
    c_when: "Publish time",
    when_asap: "As soon as approved",
    when_at: "At a set time",
    c_when_tz: "in {tz}",
    c_when_past: "This time has passed; it will be published as soon as it is approved.",
    c_preview: "Preview",
    c_preview_media: "{n} media",
    c_preview_empty: "No text yet.",
    c_preview_note: "An approximate preview; media are not displayed.",
    c_save_draft: "Save draft",
    c_submit: "Save and submit for approval",
    c_saved: "Draft saved.",
    c_submitted: "Submitted for approval.",
    c_edit_note: "Editing withdraws an earlier approval request: what gets approved is exactly what gets published.",
    c_problems: "Fix these before saving:",
    tb_label: "Text formatting",
    tb_bold: "Bold",
    tb_italic: "Italic",
    tb_underline: "Underline",
    tb_strike: "Strikethrough",
    tb_link: "Link",
    tb_code: "Code",
    tb_spoiler: "Spoiler",
    tb_quote: "Quote",
    link_prompt: "Link address",
    link_insert: "Insert link",
    pr_caption_too_long: "The text is longer than {n} characters.",
    pr_too_many_hashtags: "More than {n} hashtags.",
    pr_image_needs_one_image: "The image format needs exactly one image.",
    pr_reel_needs_one_video: "A reel needs exactly one video.",
    pr_carousel_needs_2_to_10_items: "A carousel needs 2 to 10 items.",
    pr_instagram_images_must_be_jpeg: "Instagram images must be JPEG (the address ends in .jpg or .jpeg).",
    pr_format_not_for_instagram: "This format is not for Instagram.",
    pr_instagram_supports_new_posts_only: "Only new posts are possible on Instagram.",
    pr_text_required: "The message text is empty.",
    pr_text_too_long: "The text is longer than Telegram allows.",
    pr_text_post_has_no_media: "A text post has no media; switch the format to photo, album or video.",
    pr_photo_needs_one_image: "The photo format needs exactly one image.",
    pr_video_needs_one_video: "The video format needs exactly one video.",
    pr_album_needs_2_to_10_items: "An album needs 2 to 10 items.",
    pr_format_not_for_telegram: "This format is not for Telegram.",
    pr_tag_not_allowed: "Telegram does not accept this tag: `{tag}`",
    pr_span_needs_tg_spoiler: "A span tag is accepted only for spoiler text.",
    pr_link_needs_href: "A link has no https address.",
    pr_unbalanced: "The `{tag}` tag is not closed properly.",
    pr_unclosed: "A tag is left open: `{tag}`",
    pr_bare_lt: "A lone \"<\" is not accepted; write `&lt;` instead.",
    pr_bare_ampersand: "A lone \"&\" is not accepted; write `&amp;` instead.",
    pr_media_https: "Media address {n} must start with https://.",
    pr_message_id: "Enter the message number.",
    pr_unknown: "Problem: {code}",
    a_edit: "Edit",
    a_submit: "Submit for approval",
    a_approve: "Approve publishing",
    a_reject: "Reject",
    a_reject_reason: "Reason for rejecting (optional)",
    a_reject_confirm: "Reject it",
    a_publish_now: "Publish now",
    a_retry: "Try again",
    a_cancel: "Cancel",
    a_cancel_confirm: "Cancel it?",
    a_open: "See the post",
    a_copy: "Make a new copy",
    m_approved: "Approved; it will be published at its time.",
    m_rejected: "Rejected.",
    m_publishing: "Queued for publishing…",
    m_published: "Published.",
    m_canceled: "Canceled.",
    m_submitted: "Submitted for approval.",
    m_failed: "Publishing failed:",
    approver_only: "Approving, rejecting and publishing now need the approver role.",
    requested: "Approval requested: {when}",
    decided: "Decided: {when}",
    decision_reason: "Reason: {r}",
    attempts: "{n} attempts",
    publish_at: "Publishes: {when}",
    publish_asap: "Publishes: as soon as approved",
    published_at: "Published: {when}",
    fail_reason: "Reason:",
    ou_title: "Unknown whether it was published",
    ou_body:
      "The connection dropped mid-publish. To avoid a duplicate, the panel does not send it again. Check the channel or page: if the post is not there, make a new copy from here.",
    retry_note: "It is retried automatically up to three times; after that, publish it by hand with Try again.",
    op_edit_label: "Edit message {id}",
    op_pin_label: "Pin message {id}",
    cal_more: "{n} more",
    cal_none: "Nothing is scheduled in this period.",

    db_upcoming: "Coming up",
    db_upcoming_none: "No post is queued for publishing.",
    db_awaiting: "{n} posts awaiting approval",
    db_top_findings: "Top findings",
    db_open_planner: "Planner",
    db_open_audit: "All findings",
    db_open_analytics: "Full analytics",
    ob_type: "Project type",
    ob_WEBSITE: "Website",
    ob_WEBSITE_desc: "Crawl and technical audit, keywords and speed, a WordPress or Cloudflare connection, and fixes applied with approval.",
    ob_INSTAGRAM: "Instagram page",
    ob_INSTAGRAM_desc: "Audit of the name, bio and captions for Instagram search, engagement analytics, the best time to post, competitors and scheduled publishing with approval.",
    ob_TELEGRAM: "Telegram channel",
    ob_TELEGRAM_desc: "Audit of the title and description for Telegram search, view rate, competitors and scheduled publishing with approval, through the channel's admin bot.",
    ob_handle_IG: "Page username (optional)",
    ob_handle_TG: "Channel username (optional)",
    ob_handle_help: "Only shown until the account is connected; the real name replaces it then.",
    ob_handle_invalid: "A username is 2–32 English letters, digits, dots or underscores.",
    ob_s1: "Create the project",
    ob_s2: "Connect the account",
    ob_s3: "First sync",
    ob_s4: "Audit and suggestions",
    ob_done: "Everything is ready.",
    ob_open: "Go to the profile",
    ob_lock: "No post is published and no channel title or description is changed without a person's approval — enforced in the server and the database, not just in this interface.",
  },
);

export type SocialStrings = (typeof SOCIAL)["fa"];
