import { defineDict } from "../../../lib/dict";

export const CONTENT = defineDict(
  {
    tab_docs: "سندها",
    tab_opps: "فرصت‌های Search Console",
    tabs_label: "بخش‌های محتوا",
    docs_intro:
      "متن را همین‌جا بنویس یا صفحه‌ای از سایت را وارد کن؛ هم‌زمان با نوشتن، امتیاز و فهرست بررسی بر اساس کلمه‌ی کلیدی، ساختار، خوانایی و داده‌ی واقعی Search Console و رقبا به‌روز می‌شود.",
    new_doc: "سند تازه",
    import: "وارد کردن از سایت",
    brief: "طرح محتوا",
    col_title: "عنوان",
    col_keyword: "کلمه‌ی کلیدی",
    col_lang: "زبان",
    col_score: "امتیاز",
    col_publish: "انتشار",
    col_updated: "آخرین ویرایش",
    empty: "هنوز سندی نساخته‌ای. یک سند تازه بساز یا صفحه‌ای از سایت را وارد کن.",
    lang_fa: "فارسی",
    lang_en: "انگلیسی",
    // new / import
    new_title: "سند تازه",
    title: "عنوان",
    title_placeholder: "عنوان اصلی صفحه (H1)",
    keyword: "کلمه‌ی کلیدی هدف",
    keyword_placeholder: "مثلاً: خرید کفش ورزشی",
    language: "زبان متن",
    create: "ساختن و باز کردن",
    import_title: "وارد کردن صفحه‌ای از سایت",
    import_url: "نشانی صفحه",
    import_help: "فقط صفحه‌های همین سایت. متن اصلی، عنوان و توضیحات متا جدا می‌شوند و منو و پاورقی کنار می‌روند.",
    import_submit: "وارد کردن",
    // brief
    brief_title: "طرح محتوا برای یک کلمه",
    brief_help:
      "از منابع واقعی: جستجوهای Search Console که این کلمه را دارند، صفحه‌های رقبا که درباره‌اش نوشته‌اند و زیرعنوان‌های مشترکشان، و طول هدف.",
    brief_run: "ساختن طرح",
    brief_sources: "منابع",
    brief_gsc_off: "Search Console وصل نیست؛ جستجوها و پرسش‌ها خالی‌اند.",
    brief_no_comp: "صفحه‌ای از رقبا درباره‌ی این کلمه نمونه‌برداری نشده؛ رقیب اضافه و تحلیل کن.",
    brief_target_words: "طول پیشنهادی",
    brief_words_n: "حدود {n} کلمه",
    brief_words_unknown: "داده‌ای برای مقایسه نیست",
    brief_title_len: "طول عنوان: {a} تا {b} نویسه",
    brief_desc_len: "طول توضیحات: {a} تا {b} نویسه",
    brief_outline: "ساختار پیشنهادی (زیرعنوان‌ها)",
    brief_outline_src_comp: "در {n} سایت رقیب",
    brief_outline_src_q: "پرسش واقعی کاربران",
    brief_queries: "جستجوهای مرتبط",
    brief_questions: "پرسش‌ها",
    brief_our_pages: "صفحه‌های فعلی تو برای این موضوع",
    brief_comp_pages: "صفحه‌های رقبا",
    brief_create: "ساختن سند از این طرح",
    brief_period: "Search Console، از {from} تا {to}",
    brief_empty: "چیزی پیدا نشد.",
    // editor
    back: "همه‌ی سندها",
    save: "ذخیره",
    saving: "در حال ذخیره…",
    saved: "ذخیره شده",
    unsaved: "تغییرات ذخیره نشده",
    leave_warning: "تغییرات ذخیره نشده است.",
    export: "خروجی HTML",
    delete_doc: "حذف سند",
    url: "نشانی صفحه (اختیاری)",
    url_help: "اگر این متن مال صفحه‌ی موجودی است؛ برای بررسی کلمه در نشانی و انتشار روی همان صفحه.",
    meta_title: "عنوان سئو",
    meta_title_help: "همان که در نتایج گوگل آبی دیده می‌شود؛ خالی بماند، عنوان اصلی به‌کار می‌رود.",
    meta_desc: "توضیحات متا",
    chars: "{n} نویسه",
    body: "متن",
    body_placeholder: "از اینجا بنویس…",
    // toolbar
    tb_label: "قالب‌بندی متن",
    tb_p: "پاراگراف",
    tb_h2: "زیرعنوان ۲",
    tb_h3: "زیرعنوان ۳",
    tb_bold: "درشت",
    tb_italic: "کج",
    tb_ul: "فهرست نقطه‌ای",
    tb_ol: "فهرست شماره‌دار",
    tb_quote: "نقل‌قول",
    tb_link: "پیوند",
    tb_unlink: "برداشتن پیوند",
    tb_image: "تصویر",
    tb_undo: "واگرد",
    link_url: "نشانی پیوند",
    image_url: "نشانی تصویر",
    image_alt: "متن جایگزین تصویر (alt)",
    image_alt_help: "برای صفحه‌خوان‌ها و جستجوی تصویر؛ آنچه در تصویر است را کوتاه توصیف کن.",
    insert: "درج",
    images_title: "تصویرهای متن",
    image_no_alt: "بدون متن جایگزین",
    // sidebar
    analysis: "تحلیل",
    analyzing: "در حال تحلیل…",
    score: "امتیاز محتوا",
    score_help: "مجموع وزن‌دار بررسی‌ها؛ بررسی‌ای که داده‌اش نیست حساب نمی‌شود.",
    sources: "داده‌های به‌کاررفته",
    src_gsc_on: "Search Console",
    src_gsc_off: "Search Console وصل نیست",
    src_crawl_on: "آخرین اسکن سایت",
    src_crawl_off: "اسکنی نیست",
    src_comp: "{n} صفحه‌ی رقیب",
    g_keyword: "کلمه‌ی کلیدی",
    g_meta: "عنوان و توضیحات",
    g_structure: "ساختار",
    g_length: "طول",
    g_readability: "خوانایی",
    g_links: "پیوندها",
    g_media: "تصویرها",
    g_terms: "واژه‌های مرتبط",
    serp: "پیش‌نمایش در نتایج گوگل",
    serp_help: "برآورد بر اساس عرض نمایش (پیکسل)؛ گوگل بر اساس عرض می‌بُرد نه تعداد نویسه.",
    serp_title_w: "عنوان: {px} از {max} پیکسل",
    serp_desc_w: "توضیحات: {px} از {max} پیکسل",
    serp_cut: "بریده می‌شود",
    serp_no_desc: "توضیحات متا نوشته نشده؛ گوگل تکه‌ای از متن را نشان می‌دهد.",
    kw_stats: "کلمه‌ی کلیدی",
    kw_exact: "تکرار دقیق",
    kw_variants: "شکل‌های دیگر",
    kw_density: "تراکم",
    kw_in_title: "در عنوان سئو",
    kw_in_h1: "در عنوان اصلی",
    kw_in_first: "در پاراگراف اول",
    kw_in_meta: "در توضیحات متا",
    kw_in_url: "در نشانی",
    kw_in_sub: "در زیرعنوان‌ها",
    no_keyword: "کلمه‌ی کلیدی تعیین نشده.",
    readability: "خوانایی",
    flesch: "سهولت خواندن",
    avg_sentence: "میانگین کلمه در جمله",
    long_sentences: "جمله‌های بلند",
    avg_paragraph: "میانگین کلمه در پاراگراف",
    long_paragraphs: "پاراگراف‌های بلند",
    passive: "جمله‌های مجهول (تقریبی)",
    length: "طول در برابر صفحه‌های برتر",
    words_now: "{n} کلمه",
    words_median: "میانه‌ی صفحه‌های برتر: {n} کلمه",
    no_benchmark: "برای مقایسه، Search Console را وصل کن یا رقیب اضافه کن.",
    bench_sample: "صفحه‌های مقایسه",
    bench_src_gsc: "رتبه‌ی تو",
    bench_src_tracked: "کلمه‌ی ردیابی‌شده",
    bench_src_competitor: "رقیب",
    link_sugg: "پیوند داخلی پیشنهادی",
    link_sugg_help: "صفحه‌های مرتبط سایت و متن پیوندی که با جستجوهای واقعی‌شان جور است.",
    insert_link: "درج در متن",
    no_link_sugg: "پیشنهادی نیست.",
    terms: "واژه‌های مرتبط از Search Console",
    terms_help: "واژه‌هایی که کاربران واقعی با این موضوع جستجو کرده‌اند؛ سبز یعنی در متن آمده.",
    no_terms: "Search Console وصل نیست یا جستجوی مرتبطی ندارد.",
    // publish
    publish: "انتشار در وردپرس",
    publish_help:
      "انتشار تغییر حساس است: درخواست ثبت می‌شود و کسی که اجازه‌ی تأیید دارد آن را تأیید یا رد می‌کند. هر ویرایش پس از درخواست، آن را باطل می‌کند.",
    mode: "نوع انتشار",
    mode_draft: "پیش‌نویس تازه در وردپرس",
    mode_draft_help: "یک نوشته‌ی پیش‌نویس ساخته می‌شود؛ بازدیدکننده‌ها چیزی نمی‌بینند.",
    mode_update: "جایگزینی متن صفحه‌ی موجود",
    mode_update_help: "متن و عنوان نوشته‌ای که نشانی‌اش همین نشانی سند است عوض می‌شود؛ نسخه‌ی قبلی برای بازگردانی نگه داشته می‌شود.",
    post_type: "گونه",
    post_posts: "نوشته",
    post_pages: "برگه",
    request_publish: "درخواست انتشار",
    status: "وضعیت انتشار",
    requested_at: "درخواست {when}",
    decided_at: "تصمیم {when}",
    approve: "تأیید و انتشار",
    reject: "رد",
    reject_reason: "دلیل رد (اختیاری)",
    rollback: "بازگردانی",
    view_post: "مشاهده در سایت",
    publish_error: "خطا: {e}",
    needs_wp: "برای انتشار، وردپرس را در صفحه‌ی «اتصال سایت» وصل کن.",
    needs_url: "برای جایگزینی متن صفحه‌ی موجود، نشانی صفحه را در سند وارد کن.",
    approver_only: "فقط مالک یا مدیر می‌تواند تأیید کند.",
    save_first: "اول تغییرات را ذخیره کن.",
  },
  {
    tab_docs: "Documents",
    tab_opps: "Search Console opportunities",
    tabs_label: "Content sections",
    docs_intro:
      "Write here or import a page of the site; as you type, the score and checklist update from the keyword, structure, readability, and real Search Console and competitor data.",
    new_doc: "New document",
    import: "Import from the site",
    brief: "Content brief",
    col_title: "Title",
    col_keyword: "Keyword",
    col_lang: "Language",
    col_score: "Score",
    col_publish: "Publishing",
    col_updated: "Last edited",
    empty: "No documents yet. Create one or import a page of the site.",
    lang_fa: "Persian",
    lang_en: "English",
    new_title: "New document",
    title: "Title",
    title_placeholder: "The page's main heading (H1)",
    keyword: "Target keyword",
    keyword_placeholder: "e.g. running shoes",
    language: "Text language",
    create: "Create and open",
    import_title: "Import a page of the site",
    import_url: "Page URL",
    import_help: "Only pages of this site. The main text, title and meta description are extracted; menus and footers are left out.",
    import_submit: "Import",
    brief_title: "Content brief for a keyword",
    brief_help:
      "From real sources: Search Console queries containing the keyword, competitor pages about it and the subheadings they share, and a target length.",
    brief_run: "Build the brief",
    brief_sources: "Sources",
    brief_gsc_off: "Search Console is not connected; queries and questions are empty.",
    brief_no_comp: "No competitor page about this keyword was sampled; add and analyze competitors.",
    brief_target_words: "Suggested length",
    brief_words_n: "About {n} words",
    brief_words_unknown: "No data to compare",
    brief_title_len: "Title length: {a}–{b} characters",
    brief_desc_len: "Description length: {a}–{b} characters",
    brief_outline: "Suggested outline (subheadings)",
    brief_outline_src_comp: "On {n} competitor sites",
    brief_outline_src_q: "A real user question",
    brief_queries: "Related queries",
    brief_questions: "Questions",
    brief_our_pages: "Your current pages on this topic",
    brief_comp_pages: "Competitor pages",
    brief_create: "Create a document from this brief",
    brief_period: "Search Console, {from} to {to}",
    brief_empty: "Nothing found.",
    back: "All documents",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    unsaved: "Unsaved changes",
    leave_warning: "Changes are not saved.",
    export: "Export HTML",
    delete_doc: "Delete document",
    url: "Page URL (optional)",
    url_help: "If this text belongs to an existing page; used for the keyword-in-URL check and to publish over that page.",
    meta_title: "SEO title",
    meta_title_help: "The blue line in Google's results; if empty, the main title is used.",
    meta_desc: "Meta description",
    chars: "{n} characters",
    body: "Text",
    body_placeholder: "Start writing…",
    tb_label: "Text formatting",
    tb_p: "Paragraph",
    tb_h2: "Heading 2",
    tb_h3: "Heading 3",
    tb_bold: "Bold",
    tb_italic: "Italic",
    tb_ul: "Bulleted list",
    tb_ol: "Numbered list",
    tb_quote: "Quote",
    tb_link: "Link",
    tb_unlink: "Remove link",
    tb_image: "Image",
    tb_undo: "Undo",
    link_url: "Link URL",
    image_url: "Image URL",
    image_alt: "Image alt text",
    image_alt_help: "For screen readers and image search; briefly describe what the image shows.",
    insert: "Insert",
    images_title: "Images in the text",
    image_no_alt: "No alt text",
    analysis: "Analysis",
    analyzing: "Analyzing…",
    score: "Content score",
    score_help: "A weighted sum of the checks; a check without the data it needs does not count.",
    sources: "Data used",
    src_gsc_on: "Search Console",
    src_gsc_off: "Search Console not connected",
    src_crawl_on: "The latest site scan",
    src_crawl_off: "No scan",
    src_comp: "{n} competitor pages",
    g_keyword: "Keyword",
    g_meta: "Title and description",
    g_structure: "Structure",
    g_length: "Length",
    g_readability: "Readability",
    g_links: "Links",
    g_media: "Images",
    g_terms: "Related terms",
    serp: "Preview in Google results",
    serp_help: "An estimate by display width (pixels); Google cuts by width, not by characters.",
    serp_title_w: "Title: {px} of {max} px",
    serp_desc_w: "Description: {px} of {max} px",
    serp_cut: "Truncated",
    serp_no_desc: "No meta description; Google will show a snippet of the text.",
    kw_stats: "Keyword",
    kw_exact: "Exact uses",
    kw_variants: "Other forms",
    kw_density: "Density",
    kw_in_title: "In the SEO title",
    kw_in_h1: "In the main title",
    kw_in_first: "In the first paragraph",
    kw_in_meta: "In the meta description",
    kw_in_url: "In the URL",
    kw_in_sub: "In subheadings",
    no_keyword: "No keyword set.",
    readability: "Readability",
    flesch: "Reading ease",
    avg_sentence: "Words per sentence",
    long_sentences: "Long sentences",
    avg_paragraph: "Words per paragraph",
    long_paragraphs: "Long paragraphs",
    passive: "Passive sentences (approx.)",
    length: "Length vs leading pages",
    words_now: "{n} words",
    words_median: "Leading pages' median: {n} words",
    no_benchmark: "Connect Search Console or add competitors to compare.",
    bench_sample: "Pages compared",
    bench_src_gsc: "Your ranking",
    bench_src_tracked: "Tracked keyword",
    bench_src_competitor: "Competitor",
    link_sugg: "Suggested internal links",
    link_sugg_help: "Related pages of the site, with anchor text matching their real queries.",
    insert_link: "Insert in text",
    no_link_sugg: "No suggestions.",
    terms: "Related terms from Search Console",
    terms_help: "Terms real users searched around this topic; green means the text uses it.",
    no_terms: "Search Console is not connected or has no related queries.",
    publish: "Publish to WordPress",
    publish_help:
      "Publishing is a sensitive change: a request is recorded and someone allowed to approve decides it. Any edit after the request voids it.",
    mode: "How to publish",
    mode_draft: "A new WordPress draft",
    mode_draft_help: "A draft post is created; visitors see nothing.",
    mode_update: "Replace the text of the existing page",
    mode_update_help: "The title and text of the post at this document's URL are replaced; the previous version is kept for rollback.",
    post_type: "Type",
    post_posts: "Post",
    post_pages: "Page",
    request_publish: "Request publishing",
    status: "Publishing status",
    requested_at: "Requested {when}",
    decided_at: "Decided {when}",
    approve: "Approve and publish",
    reject: "Reject",
    reject_reason: "Reason (optional)",
    rollback: "Roll back",
    view_post: "View on the site",
    publish_error: "Error: {e}",
    needs_wp: "Connect WordPress on the Connect site screen to publish.",
    needs_url: "To replace an existing page's text, set the page URL on the document.",
    approver_only: "Only an owner or admin can approve.",
    save_first: "Save your changes first.",
  },
);

export type ContentStrings = (typeof CONTENT)["fa"];
