/**
 * PDF reports: generated by the worker's `report-generate` job (on request or
 * by the project's monthly "report" schedule), stored in `reports.content`
 * (bytea, at most 10 MB — the deployment has no object storage; a CHECK in the
 * database enforces the cap), listed and downloaded by the panel, and
 * announced with an in-app notification when ready.
 *
 * White label: the organisation's report brand (name, logo as an image data
 * URL, colour) is stored on the organisation and copied onto each report row,
 * so an old report still shows the brand it was made with.
 */
import { z } from "zod";
import { and, db, desc, eq, organizations, REPORT_MAX_BYTES, reports, type Report, type ReportBrand, type ReportKind } from "@seo/db";
import { BadRequest, NotFound, childLogger, dataQueue, type ReportJobData } from "@seo/core";
import { notify } from "../notifications.js";
import type { Deps } from "../deps.js";
import { projectById } from "../site.js";
import { collectFacts } from "./data.js";
import { footerTemplate, renderReportHtml } from "./templates.js";
import type { ReportLocale } from "./kit.js";

export const REPORT_KINDS: readonly ReportKind[] = ["audit", "executive", "keywords"];
const MAX_LOGO_BYTES = 300 * 1024;

export const brandInput = z.object({
  name: z.string().trim().max(100).nullable().optional(),
  color: z
    .string()
    .trim()
    .regex(/^#[0-9a-fA-F]{6}$/, "A colour like #0e9a5c")
    .nullable()
    .optional(),
  logo: z
    .string()
    .max(Math.ceil((MAX_LOGO_BYTES * 4) / 3) + 64)
    .regex(/^data:image\/(png|jpeg|webp|svg\+xml);base64,[A-Za-z0-9+/=]+$/, "A PNG, JPEG, WebP or SVG image as a base64 data URL")
    .nullable()
    .optional(),
});

export async function getBrand(orgId: string): Promise<ReportBrand & { defaults: { name: string } }> {
  const org = (await db.select({ name: organizations.name, brand: organizations.reportBrand }).from(organizations).where(eq(organizations.id, orgId)).limit(1))[0];
  if (!org) throw new NotFound("Organization not found");
  return { ...(org.brand ?? {}), defaults: { name: org.name } };
}

export async function setBrand(orgId: string, input: z.infer<typeof brandInput>): Promise<ReportBrand> {
  const current = (await db.select({ brand: organizations.reportBrand }).from(organizations).where(eq(organizations.id, orgId)).limit(1))[0];
  if (!current) throw new NotFound("Organization not found");
  const next: ReportBrand = { ...(current.brand ?? {}) };
  for (const k of ["name", "color", "logo"] as const) {
    const v = input[k];
    if (v === undefined) continue;
    if (v === null || v === "") delete next[k];
    else next[k] = v;
  }
  if (next.logo && Buffer.from(next.logo.split(",")[1] ?? "", "base64").length > MAX_LOGO_BYTES) {
    throw new BadRequest("The logo is larger than 300 KB", { field: "logo" });
  }
  await db.update(organizations).set({ reportBrand: Object.keys(next).length ? next : null }).where(eq(organizations.id, orgId));
  return next;
}

export type PdfPrinter = (html: string, opts: { footerTemplate: string; headerTemplate: string }) => Promise<Buffer>;

function fileName(projectName: string, kind: ReportKind, now: Date): string {
  const slug = projectName
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "site";
  return `${slug}-${kind}-${now.toISOString().slice(0, 10)}.pdf`;
}

/** Build and store one report. Returns the new row without its content. */
export async function generateReport(
  input: { projectId: string; kind: ReportKind; locale?: ReportLocale; createdById: string | null },
  printer: PdfPrinter,
  deps: Partial<Deps> = {},
): Promise<Omit<Report, "content">> {
  const project = await projectById(input.projectId);
  const locale: ReportLocale = input.locale ?? (project.locale === "en" ? "en" : "fa");
  const brand = await getBrand(project.orgId);
  const reportBrand: ReportBrand = { name: brand.name ?? brand.defaults.name, ...(brand.color ? { color: brand.color } : {}), ...(brand.logo ? { logo: brand.logo } : {}) };
  const facts = await collectFacts(project.id, input.kind, reportBrand, deps);
  const html = renderReportHtml(facts, locale);
  const pdf = await printer(html, { footerTemplate: footerTemplate(facts, locale), headerTemplate: "<span></span>" });
  if (pdf.length > REPORT_MAX_BYTES) {
    throw new BadRequest(`The report is ${Math.round(pdf.length / 1024 / 1024)} MB, over the 10 MB limit; use a smaller logo`);
  }
  const row = (
    await db
      .insert(reports)
      .values({
        projectId: project.id,
        kind: input.kind,
        runId: facts.audit.run?.id ?? null,
        fileKey: fileName(project.name, input.kind, facts.generatedAt),
        contentType: "application/pdf",
        bytes: pdf.length,
        content: pdf,
        brand: reportBrand,
        createdById: input.createdById,
      })
      .returning({
        id: reports.id,
        projectId: reports.projectId,
        kind: reports.kind,
        runId: reports.runId,
        fileKey: reports.fileKey,
        contentType: reports.contentType,
        bytes: reports.bytes,
        brand: reports.brand,
        createdById: reports.createdById,
        createdAt: reports.createdAt,
      })
  )[0]!;
  return row;
}

const KIND_TEXT: Record<ReportKind, { fa: string; en: string }> = {
  audit: { fa: "ممیزی سئو", en: "SEO audit" },
  executive: { fa: "مدیریتی", en: "executive" },
  keywords: { fa: "کلمات کلیدی", en: "keyword" },
};

/**
 * The `report-generate` job: generate, store, notify. A person's request
 * records them as the creator; a scheduled one is "scheduler". The
 * notification is keyed by the report, so a retried job never announces twice.
 */
export async function runReportJob(data: ReportJobData, printer: PdfPrinter, deps: Partial<Deps> = {}): Promise<{ reportId: string; bytes: number }> {
  const log = childLogger({ component: "report-job", projectId: data.projectId, kind: data.kind, correlationId: data.correlationId });
  const project = await projectById(data.projectId);
  const createdById = data.requestedBy === "scheduler" ? null : data.requestedBy;
  const report = await generateReport(
    { projectId: data.projectId, kind: data.kind, ...(data.locale ? { locale: data.locale } : {}), createdById },
    printer,
    deps,
  );
  await notify({
    orgId: project.orgId,
    projectId: project.id,
    rule: null,
    event: {
      kind: "report_ready",
      severity: "INFO",
      title: { fa: `گزارش ${KIND_TEXT[data.kind].fa} آماده است`, en: `The ${KIND_TEXT[data.kind].en} report is ready` },
      body: {
        fa: `گزارش ${KIND_TEXT[data.kind].fa} «${project.name}»${data.trigger === "SCHEDULE" ? " (زمان‌بندی‌شده)" : ""} ساخته شد و آمادهٔ دریافت است.`,
        en: `The ${KIND_TEXT[data.kind].en} report for "${project.name}"${data.trigger === "SCHEDULE" ? " (scheduled)" : ""} is ready to download.`,
      },
      link: `/reports?project=${project.id}`,
      data: { reportId: report.id, kind: data.kind, bytes: report.bytes, trigger: data.trigger },
      dedupeKey: `report_ready:${report.id}`,
    },
  });
  log.info({ reportId: report.id, bytes: report.bytes }, "report generated");
  return { reportId: report.id, bytes: report.bytes };
}

export type ReportSummary = Omit<Report, "content" | "brand"> & { brandName: string | null };

export async function listReports(projectId: string): Promise<ReportSummary[]> {
  const rows = await db
    .select({
      id: reports.id,
      projectId: reports.projectId,
      kind: reports.kind,
      runId: reports.runId,
      fileKey: reports.fileKey,
      contentType: reports.contentType,
      bytes: reports.bytes,
      brand: reports.brand,
      createdById: reports.createdById,
      createdAt: reports.createdAt,
    })
    .from(reports)
    .where(eq(reports.projectId, projectId))
    .orderBy(desc(reports.createdAt))
    .limit(200);
  return rows.map(({ brand, ...r }) => ({ ...r, brandName: brand?.name ?? null }));
}

export async function reportFile(projectId: string, id: string): Promise<{ fileKey: string; contentType: string; content: Buffer; kind: ReportKind }> {
  const row = (
    await db
      .select({ fileKey: reports.fileKey, contentType: reports.contentType, content: reports.content, kind: reports.kind })
      .from(reports)
      .where(and(eq(reports.id, id), eq(reports.projectId, projectId)))
      .limit(1)
  )[0];
  if (!row) throw new NotFound("Report not found");
  return row;
}

export async function deleteReport(projectId: string, id: string): Promise<void> {
  const gone = await db.delete(reports).where(and(eq(reports.id, id), eq(reports.projectId, projectId))).returning({ id: reports.id });
  if (!gone[0]) throw new NotFound("Report not found");
}

export type ReportJobView = {
  jobId: string;
  kind: ReportKind;
  state: string;
  queuedAt: string;
  reportId: string | null;
  error: string | null;
};

/** Reports being generated for a project (waiting, running, or retrying after a failure). */
export async function pendingJobs(projectId: string): Promise<ReportJobView[]> {
  const jobs = await dataQueue("report").getJobs(["waiting", "active", "delayed", "prioritized"], 0, 200);
  const out: ReportJobView[] = [];
  for (const j of jobs) {
    if (!j || j.data.projectId !== projectId) continue;
    out.push({ jobId: j.id ?? "", kind: j.data.kind, state: await j.getState(), queuedAt: new Date(j.timestamp).toISOString(), reportId: null, error: j.failedReason || null });
  }
  return out;
}

/** One job's state, only if it belongs to the project (another project's job answers "not found"). */
export async function jobStatus(projectId: string, jobId: string): Promise<ReportJobView> {
  const job = await dataQueue("report").getJob(jobId);
  if (!job || job.data.projectId !== projectId) throw new NotFound("Report job not found");
  const result = job.returnvalue as { reportId?: string } | null | undefined;
  return {
    jobId,
    kind: job.data.kind,
    state: await job.getState(),
    queuedAt: new Date(job.timestamp).toISOString(),
    reportId: result?.reportId ?? null,
    error: job.failedReason || null,
  };
}
