import { defineDict } from "../../../lib/dict";

export const ALERTS = defineDict(
  {
    tab_notifications: "اعلان‌ها",
    tab_rules: "قاعده‌های هشدار",
    tab_schedules: "زمان‌بندی کارها",
    tabs_label: "بخش‌های هشدار",
    // notifications
    n_unread_only: "فقط خوانده‌نشده‌ها",
    n_mark_all: "همه خوانده شد",
    n_mark_read: "خوانده شد",
    n_empty: "اعلانی نیست. وقتی امتیاز افت کند، مشکل بحرانی تازه‌ای پیدا شود، رتبه‌ای پایین بیاید یا گزارشی آماده شود اینجا خبر می‌گیری.",
    n_open: "باز کردن",
    n_more: "بیشتر",
    n_delivery: "ارسال",
    n_sent: "ارسال شد",
    n_failed: "ناموفق",
    n_pending: "در صف",
    n_skipped: "رد شد",
    // rules
    r_intro:
      "هر قاعده می‌گوید کِی و از کجا خبر بگیری. همه‌ی قاعده‌ها داخل پنل اعلان می‌دهند؛ وب‌هوک امضاشده و تلگرام اختیاری‌اند.",
    r_new: "قاعده‌ی تازه",
    r_kind: "رویداد",
    r_threshold: "آستانه",
    r_no_threshold: "آستانه ندارد",
    r_channels: "کانال‌ها",
    r_webhook_url: "نشانی وب‌هوک",
    r_webhook_help: "درخواست `POST` با بدنه‌ی JSON؛ سرآیند امضا با کلید مخفی همین قاعده (`HMAC`) ساخته می‌شود.",
    r_enabled: "فعال",
    r_disabled: "غیرفعال",
    r_create: "ساختن قاعده",
    r_save: "ذخیره",
    r_test: "ارسال آزمایشی",
    r_test_ok: "{channel}: رسید.",
    r_test_fail: "{channel}: نرسید — {reason}",
    r_test_none: "این قاعده کانال بیرونی ندارد؛ اعلان آزمایشی داخل پنل ثبت شد.",
    r_secret_title: "کلید امضای وب‌هوک",
    r_secret_once: "این کلید فقط همین یک بار نمایش داده می‌شود. آن را در سرویس دریافت‌کننده ذخیره کن تا امضای هر درخواست را بررسی کند.",
    r_rotate: "کلید تازه",
    r_has_secret: "کلید امضا دارد",
    r_telegram_missing: "تلگرام برای سازمان تنظیم نشده؛ پیام‌ها ارسال نمی‌شوند تا مدیر آن را در تنظیمات ← سرویس‌ها وصل کند.",
    r_empty: "قاعده‌ای نیست.",
    r_open_integrations: "تنظیمات سرویس‌ها",
    r_default: "پیش‌فرض: {n}",
    // schedules
    s_intro: "کارهای خودکار این پروژه. زمان‌ها در منطقه‌ی زمانی‌ای که انتخاب می‌کنی اجرا می‌شوند؛ حداقل فاصله یک ساعت است.",
    s_kind: "کار",
    s_when: "زمان اجرا",
    s_timezone: "منطقه‌ی زمانی",
    s_next: "اجرای بعدی",
    s_last: "آخرین اجرا",
    s_last_error: "آخرین خطا",
    s_preset_hourly: "هر ساعت",
    s_preset_every: "هر چند ساعت",
    s_preset_daily: "هر روز",
    s_preset_weekly: "هر هفته",
    s_preset_monthly: "هر ماه",
    s_preset_custom: "عبارت زمان‌بندی دلخواه",
    s_every_n: "هر {n} ساعت",
    s_hours: "ساعت",
    s_at: "ساعت اجرا",
    s_minute: "دقیقه",
    s_weekday: "روز هفته",
    s_monthday: "روز ماه",
    s_cron: "عبارت پنج‌بخشی",
    s_cron_help: "دقیقه، ساعت، روز ماه، ماه، روز هفته — مثل `0 3 * * 1`.",
    s_saved: "زمان‌بندی ذخیره شد.",
    s_invalid_cron: "این عبارت زمان‌بندی معتبر نیست یا بیش از یک بار در ساعت اجرا می‌شود.",
    s_invalid_tz: "این منطقه‌ی زمانی شناخته نیست.",
    s_scan_active: "اسکنی در حال اجرا بود؛ این نوبت رد شد.",
    day_0: "یکشنبه",
    day_1: "دوشنبه",
    day_2: "سه‌شنبه",
    day_3: "چهارشنبه",
    day_4: "پنجشنبه",
    day_5: "جمعه",
    day_6: "شنبه",
    tz_UTC: "زمان هماهنگ جهانی",
    "tz_Asia/Tehran": "تهران",
    "tz_Asia/Dubai": "دبی",
    "tz_Asia/Kabul": "کابل",
    "tz_Europe/Istanbul": "استانبول",
    "tz_Europe/London": "لندن",
    "tz_Europe/Berlin": "برلین",
    "tz_America/New_York": "نیویورک",
    "tz_America/Los_Angeles": "لس‌آنجلس",
    "tz_Asia/Tokyo": "توکیو",
    "tz_Australia/Sydney": "سیدنی",
  },
  {
    tab_notifications: "Notifications",
    tab_rules: "Alert rules",
    tab_schedules: "Schedules",
    tabs_label: "Alert sections",
    n_unread_only: "Unread only",
    n_mark_all: "Mark all read",
    n_mark_read: "Mark read",
    n_empty: "No notifications. You hear here when the score drops, a new critical issue appears, a ranking falls or a report is ready.",
    n_open: "Open",
    n_more: "More",
    n_delivery: "Delivery",
    n_sent: "Sent",
    n_failed: "Failed",
    n_pending: "Queued",
    n_skipped: "Skipped",
    r_intro:
      "Each rule says when and where you hear about something. Every rule notifies inside the panel; a signed webhook and Telegram are optional.",
    r_new: "New rule",
    r_kind: "Event",
    r_threshold: "Threshold",
    r_no_threshold: "No threshold",
    r_channels: "Channels",
    r_webhook_url: "Webhook URL",
    r_webhook_help: "A `POST` with a JSON body; the signature header is an `HMAC` with this rule's secret.",
    r_enabled: "On",
    r_disabled: "Off",
    r_create: "Create rule",
    r_save: "Save",
    r_test: "Send a test",
    r_test_ok: "{channel}: delivered.",
    r_test_fail: "{channel}: not delivered — {reason}",
    r_test_none: "This rule has no outside channel; a test notification was recorded in the panel.",
    r_secret_title: "Webhook signing secret",
    r_secret_once: "This secret is shown only this once. Store it in the receiving service so it can verify each request's signature.",
    r_rotate: "New secret",
    r_has_secret: "Has a signing secret",
    r_telegram_missing: "Telegram is not set up for the organization; messages are not sent until an admin connects it under Settings → Integrations.",
    r_empty: "No rules.",
    r_open_integrations: "Integration settings",
    r_default: "Default: {n}",
    s_intro: "This project's automatic jobs. Times run in the time zone you choose; the minimum interval is one hour.",
    s_kind: "Job",
    s_when: "When",
    s_timezone: "Time zone",
    s_next: "Next run",
    s_last: "Last run",
    s_last_error: "Last error",
    s_preset_hourly: "Every hour",
    s_preset_every: "Every few hours",
    s_preset_daily: "Every day",
    s_preset_weekly: "Every week",
    s_preset_monthly: "Every month",
    s_preset_custom: "Custom schedule expression",
    s_every_n: "Every {n} hours",
    s_hours: "Hours",
    s_at: "At",
    s_minute: "Minute",
    s_weekday: "Weekday",
    s_monthday: "Day of month",
    s_cron: "Five-field expression",
    s_cron_help: "Minute, hour, day of month, month, weekday — e.g. `0 3 * * 1`.",
    s_saved: "Schedule saved.",
    s_invalid_cron: "That schedule expression is not valid or runs more than once an hour.",
    s_invalid_tz: "That time zone is not known.",
    s_scan_active: "A scan was already running; this run was skipped.",
    day_0: "Sunday",
    day_1: "Monday",
    day_2: "Tuesday",
    day_3: "Wednesday",
    day_4: "Thursday",
    day_5: "Friday",
    day_6: "Saturday",
    tz_UTC: "Coordinated Universal Time",
    "tz_Asia/Tehran": "Tehran",
    "tz_Asia/Dubai": "Dubai",
    "tz_Asia/Kabul": "Kabul",
    "tz_Europe/Istanbul": "Istanbul",
    "tz_Europe/London": "London",
    "tz_Europe/Berlin": "Berlin",
    "tz_America/New_York": "New York",
    "tz_America/Los_Angeles": "Los Angeles",
    "tz_Asia/Tokyo": "Tokyo",
    "tz_Australia/Sydney": "Sydney",
  },
);

export type AlertStrings = (typeof ALERTS)["fa"];
export const TIMEZONES = ["Asia/Tehran", "UTC", "Asia/Dubai", "Asia/Kabul", "Europe/Istanbul", "Europe/London", "Europe/Berlin", "America/New_York", "America/Los_Angeles", "Asia/Tokyo", "Australia/Sydney"] as const;
