import { defineDict } from "../../../lib/dict";

export const PAGESPEED = defineDict(
  {
    intro:
      "امتیاز عملکرد و Core Web Vitals مهم‌ترین صفحه‌های سایت، از PageSpeed Insights گوگل. وقتی گوگل داده‌ی کاربران واقعی دارد، قبولی یا ردی بر همان اساس است؛ وگرنه نتیجه‌ی آزمایشگاهی با برچسب خودش نشان داده می‌شود.",
    run: "سنجش سرعت",
    running: "در حال سنجش…",
    mobile: "موبایل",
    desktop: "رایانه",
    strategy: "دستگاه",
    avg_score: "میانگین امتیاز عملکرد",
    passed: "قبول در Core Web Vitals",
    failed: "رد در Core Web Vitals",
    last_run: "آخرین سنجش",
    pages_n: "{n} صفحه",
    col_page: "صفحه",
    col_score: "امتیاز",
    col_cwv: "Core Web Vitals",
    col_basis: "مبنا",
    col_when: "زمان سنجش",
    pass: "قبول",
    fail: "رد",
    basis_field_url: "کاربران واقعی این صفحه",
    basis_field_origin: "کاربران واقعی کل سایت",
    basis_lab: "آزمایشگاهی (بدون INP)",
    basis_help:
      "گوگل رتبه‌بندی را بر اساس تجربه‌ی کاربران واقعی (۷۵ درصد بازدیدها در ۲۸ روز) انجام می‌دهد. اگر این داده نباشد، یک بار سنجش آزمایشگاهی فقط LCP و CLS را می‌سنجد.",
    empty: "هنوز هیچ صفحه‌ای سنجیده نشده. یک سنجش اجرا کن؛ هر صفحه برای موبایل و رایانه جدا سنجیده می‌شود و حدود نیم دقیقه طول می‌کشد.",
    empty_strategy: "برای این دستگاه هنوز سنجشی نیست.",
    key_none:
      "سنجش‌ها بدون کلید API و با سهمیه‌ی مشترک گوگل انجام می‌شود. برای سنجش‌های بیشتر، کلید PageSpeed را در تنظیمات ← سرویس‌ها وارد کن.",
    key_org: "با کلید PageSpeed سازمان سنجیده می‌شود.",
    key_env: "با کلید PageSpeed سرور سنجیده می‌شود.",
    // run dialog
    run_title: "سنجش سرعت صفحه‌ها",
    run_default: "صفحه‌ی اصلی و پربازدیدترین صفحه‌ها",
    run_default_help: "صفحه‌هایی که بیشترین کلیک Search Console را دارند، یا در نبود آن، مهم‌ترین صفحه‌های آخرین اسکن.",
    run_custom: "صفحه‌هایی که انتخاب می‌کنم",
    run_custom_help: "تا ۱۰ نشانی از همین سایت.",
    add_url: "افزودن نشانی",
    url_placeholder: "نشانی کامل صفحه",
    url_not_on_site: "این نشانی روی همین سایت نیست.",
    url_limit: "حداکثر ۱۰ نشانی.",
    start: "شروع سنجش",
    run_started: "سنجش در صف است؛ هر صفحه حدود نیم دقیقه طول می‌کشد.",
    run_done: "سنجش تمام شد: {n} اندازه‌گیری ثبت شد.",
    run_failed_pages: "این صفحه‌ها سنجیده نشدند:",
    run_all_failed: "هیچ صفحه‌ای سنجیده نشد.",
    run_job_failed: "سنجش ناموفق بود. چند دقیقه‌ی دیگر دوباره تلاش کن.",
    // detail
    trend: "روند امتیاز عملکرد",
    trend_lcp: "روند LCP",
    no_trend: "برای روند دست‌کم دو سنجش لازم است.",
    metrics: "شاخص‌ها",
    metric: "شاخص",
    field: "کاربران واقعی (صدک ۷۵)",
    lab: "آزمایشگاه",
    rating: "ارزیابی",
    opportunities: "مهم‌ترین فرصت‌های بهبود",
    opportunities_help: "برآورد خود Lighthouse از صرفه‌جویی در زمان بارگذاری یا حجم.",
    no_opportunities: "Lighthouse فرصت بهبود مهمی پیدا نکرد.",
    saves_ms: "صرفه‌جویی حدود {v}",
    saves_bytes: "کاهش حدود {v}",
    unknown_audit: "بهبود پیشنهادی Lighthouse",
    fcp: "اولین نمایش محتوا",
    ttfb: "زمان تا اولین بایت",
    tbt: "زمان مسدود شدن رشته‌ی اصلی",
    lcp: "بزرگ‌ترین نمایش محتوا",
    inp: "تأخیر پاسخ به تعامل",
    cls: "جابه‌جایی چیدمان",
    change: "تغییر نسبت به سنجش قبلی",
    open_psi: "باز کردن در PageSpeed Insights",
  },
  {
    intro:
      "Performance score and Core Web Vitals for the site's most important pages, from Google PageSpeed Insights. When Google has real-user data the pass/fail is based on it; otherwise the lab result is shown with its own label.",
    run: "Measure speed",
    running: "Measuring…",
    mobile: "Mobile",
    desktop: "Desktop",
    strategy: "Device",
    avg_score: "Average performance score",
    passed: "Pass Core Web Vitals",
    failed: "Fail Core Web Vitals",
    last_run: "Last measured",
    pages_n: "{n} pages",
    col_page: "Page",
    col_score: "Score",
    col_cwv: "Core Web Vitals",
    col_basis: "Basis",
    col_when: "Measured",
    pass: "Pass",
    fail: "Fail",
    basis_field_url: "Real users of this page",
    basis_field_origin: "Real users of the whole site",
    basis_lab: "Lab (no INP)",
    basis_help:
      "Google ranks on real users' experience (the 75th percentile of visits over 28 days). Without that data, a single lab run measures LCP and CLS only.",
    empty: "No page has been measured yet. Run a measurement; each page is measured for mobile and desktop and takes about half a minute.",
    empty_strategy: "Nothing measured for this device yet.",
    key_none:
      "Measurements run without an API key, on Google's shared quota. For more, add a PageSpeed key under Settings → Integrations.",
    key_org: "Measured with the organization's PageSpeed key.",
    key_env: "Measured with the server's PageSpeed key.",
    run_title: "Measure page speed",
    run_default: "The homepage and the most visited pages",
    run_default_help: "The pages with the most Search Console clicks or, without it, the most important pages of the latest scan.",
    run_custom: "Pages I choose",
    run_custom_help: "Up to 10 URLs on this site.",
    add_url: "Add URL",
    url_placeholder: "Full page URL",
    url_not_on_site: "That URL is not on this site.",
    url_limit: "At most 10 URLs.",
    start: "Start",
    run_started: "Queued; each page takes about half a minute.",
    run_done: "Finished: {n} measurements recorded.",
    run_failed_pages: "These pages could not be measured:",
    run_all_failed: "No page could be measured.",
    run_job_failed: "The measurement failed. Try again in a few minutes.",
    trend: "Performance score trend",
    trend_lcp: "LCP trend",
    no_trend: "A trend needs at least two measurements.",
    metrics: "Metrics",
    metric: "Metric",
    field: "Real users (75th percentile)",
    lab: "Lab",
    rating: "Rating",
    opportunities: "Top opportunities",
    opportunities_help: "Lighthouse's own estimate of the time or bytes each would save.",
    no_opportunities: "Lighthouse found no significant opportunity.",
    saves_ms: "Saves about {v}",
    saves_bytes: "Saves about {v}",
    unknown_audit: "Lighthouse suggestion",
    fcp: "First Contentful Paint",
    ttfb: "Time to First Byte",
    tbt: "Total Blocking Time",
    lcp: "Largest Contentful Paint",
    inp: "Interaction to Next Paint",
    cls: "Cumulative Layout Shift",
    change: "Change since the previous measurement",
    open_psi: "Open in PageSpeed Insights",
  },
);

export type PageSpeedStrings = (typeof PAGESPEED)["fa"];
