import { defineDict } from "../../../lib/dict";

export const TOOLS = defineDict(
  {
    nav_label: "ابزارهای فنی",
    t_schema: "نشانه‌گذاری ساختاریافته",
    t_links: "لینک‌های داخلی",
    t_robots: "robots.txt",
    t_sitemap: "نقشه‌ی سایت",
    d_schema: "JSON-LD برای مقاله، محصول، پرسش‌های متداول، کسب‌وکار محلی و … بساز، اعتبارسنجی کن و با تأیید روی سایت بگذار.",
    d_links: "اعتبار هر صفحه در ساختار لینک‌ها، صفحه‌های یتیم، صفحه‌های مهمِ کم‌لینک و پیشنهاد لینک با متن پیوند.",
    d_robots: "فایل فعلی، آزمون نشانی‌ها برای هر خزنده، ویرایش با مقایسه‌ی خط‌به‌خط و هشدار صفحه‌های مهمی که تازه مسدود می‌شوند.",
    d_sitemap: "نقشه‌ی سایت را از آخرین اسکن بساز، نقشه‌های فعلی را اعتبارسنجی کن، روی سایت بگذار و به Search Console بفرست.",
    open_tool: "باز کردن",
    // shared
    page_url: "نشانی صفحه",
    load: "بارگذاری",
    apply_title: "اعمال روی سایت",
    apply_help: "یک پیشنهاد اصلاح حساس ساخته می‌شود؛ پس از تأیید در صف تأیید، از همان مسیری که اصلاح‌ها اعمال می‌شوند نوشته می‌شود و قابل بازگردانی است.",
    propose: "ساختن پیشنهاد اصلاح",
    target_cf: "لبه‌ی Cloudflare",
    target_wp: "وردپرس",
    target_ok: "{target} وصل است و این تغییر را پشتیبانی می‌کند.",
    target_unsupported: "{target} وصل است اما این نوع تغییر را پشتیبانی نمی‌کند.",
    target_missing: "{target} وصل نیست.",
    download_file: "دانلود فایل",
    issues: "مشکلات",
    no_issues: "مشکلی پیدا نشد.",
    line_n: "خط {n}",
    // schema
    sc_pick_type: "نوع نشانه‌گذاری",
    sc_existing: "نشانه‌گذاری فعلی صفحه",
    sc_existing_none: "این صفحه در آخرین اسکن نشانه‌گذاری JSON-LD نداشت.",
    sc_not_crawled: "این نشانی در آخرین اسکن دیده نشد؛ برای مقایسه با نشانه‌گذاری فعلی، نشانی یکی از صفحه‌های اسکن‌شده را وارد کن.",
    sc_prefilled: "از داده‌های صفحه پر شد:",
    sc_from_crawl: "اسکن سایت",
    sc_from_markup: "نشانه‌گذاری فعلی صفحه",
    sc_form: "مشخصات",
    sc_preview: "خروجی JSON-LD",
    sc_validation: "اعتبارسنجی بر اساس مستندات گوگل",
    sc_conflicts: "تداخل با نشانه‌گذاری فعلی",
    sc_valid: "بدون خطا؛ آماده‌ی اعمال.",
    sc_has_errors: "تا خطاها رفع نشوند، اعمال ممکن نیست.",
    sc_render: "پیش‌نمایش در مرورگر پنل",
    sc_render_help: "صفحه‌ی واقعی با این نشانه‌گذاری در مرورگر پنل باز می‌شود؛ چیزی روی سایت نوشته نمی‌شود.",
    sc_render_run: "باز کردن صفحه با این نشانه‌گذاری",
    sc_render_types: "نوع‌هایی که صفحه پس از این تغییر اعلام می‌کند:",
    sc_render_none: "هیچ نشانه‌گذاری‌ای دیده نشد.",
    sc_paste: "اعتبارسنجی نشانه‌گذاری دستی",
    sc_paste_help: "JSON-LD نوشته‌شده یا رونوشت‌شده از جای دیگر را اینجا بگذار.",
    sc_paste_run: "اعتبارسنجی",
    sc_paste_invalid: "این متن JSON معتبر نیست.",
    sc_add_row: "افزودن ردیف",
    sc_fill_rows: "در ردیف‌ها این فیلدهای لازم خالی‌اند: {f}",
    sc_remove_row: "حذف ردیف",
    sc_add_item: "افزودن",
    sc_type_n: "{t}",
    // internal links
    il_intro:
      "اعتبار هر صفحه با الگوریتم پیج‌رنک روی لینک‌های داخلی آخرین اسکن محاسبه می‌شود (۰ تا ۱۰۰). صفحه‌ی یتیم هیچ لینک داخلی ندارد؛ صفحه‌ی کم‌لینک در Search Console کلیک می‌گیرد اما اعتبار کمی دریافت می‌کند.",
    il_pages: "صفحه",
    il_links: "لینک داخلی",
    il_nofollow: "لینک nofollow",
    il_orphans: "صفحه‌ی یتیم",
    il_weak: "صفحه‌ی مهمِ کم‌لینک",
    il_top_share: "سهم ۱۰٪ قوی‌ترین صفحه‌ها از اعتبار",
    il_histogram: "پراکندگی تعداد لینک ورودی",
    il_histogram_help: "چند صفحه چند لینک داخلی ورودی دارند.",
    il_top: "مهم‌ترین صفحه‌ها",
    il_equity: "اعتبار",
    il_inlinks: "ورودی",
    il_outlinks: "خروجی",
    il_depth: "عمق",
    il_clicks: "کلیک",
    il_suggestions: "پیشنهاد لینک",
    il_sugg_help: "از کدام صفحه‌ی قوی به کدام صفحه لینک بده، با متن پیوندی که از جستجوهای واقعی یا عنوان صفحه آمده.",
    il_from: "از صفحه",
    il_to: "به صفحه",
    il_anchor: "متن پیوند",
    il_reason: "دلیل",
    il_none: "موردی نیست.",
    il_page_view: "بررسی یک صفحه",
    il_inbound: "لینک‌های ورودی",
    il_outbound: "لینک‌های خروجی",
    il_link_from: "صفحه‌هایی که بهتر است به این صفحه لینک بدهند",
    il_link_to: "صفحه‌های مرتبطی که این صفحه می‌تواند به آن‌ها لینک بدهد",
    il_not_indexable: "غیرقابل ایندکس",
    il_importance_gsc: "اهمیت از روی کلیک‌های Search Console",
    il_importance_none: "Search Console وصل نیست؛ صفحه‌های کم‌لینک بر اساس کلیک تشخیص داده نمی‌شوند.",
    il_scanned: "آخرین اسکن {when}",
    // robots
    rb_current: "فایل فعلی",
    rb_state_ok: "در دسترس",
    rb_state_missing: "وجود ندارد (همه‌چیز مجاز)",
    rb_state_unreachable: "در دسترس نیست (گوگل خزش را متوقف می‌کند)",
    rb_empty: "فایل خالی است.",
    rb_suggested: "این سایت robots.txt ندارد؛ یک فایل پایه پیشنهاد شده است.",
    rb_tester: "آزمون نشانی‌ها",
    rb_tester_help: "هر خط یک نشانی یا مسیر. پاسخ با همان تجزیه‌گر robots.txt خزنده‌ی پنل (استاندارد `RFC 9309`) داده می‌شود.",
    rb_agents: "خزنده‌ها",
    rb_agent_custom: "خزنده‌ی دیگر",
    rb_against: "بر اساس",
    rb_against_live: "فایل فعلی",
    rb_against_edit: "نسخه‌ی ویرایش‌شده",
    rb_test_run: "آزمون",
    rb_allowed: "مجاز",
    rb_blocked: "مسدود",
    rb_rule: "قاعده",
    rb_no_rule: "هیچ قاعده‌ای منطبق نشد (مجاز)",
    rb_group: "گروه",
    rb_editor: "ویرایش",
    rb_review: "بررسی تغییرات",
    rb_diff: "تفاوت با فایل فعلی",
    rb_no_diff: "تغییری نسبت به فایل فعلی نیست.",
    rb_newly_blocked: "صفحه‌های مهمی که با این نسخه برای Googlebot مسدود می‌شوند",
    rb_newly_blocked_help: "این پیشنهاد به‌خاطر مسدود کردن این صفحه‌ها «نیازمند تأیید» می‌شود.",
    rb_newly_allowed: "{n} صفحه که الان مسدود است با این نسخه مجاز می‌شود.",
    rb_checked: "{n} نشانی مهم بررسی شد.",
    rb_reset: "بازگشت به فایل فعلی",
    // sitemap
    sm_generated: "نقشه‌ی ساخته‌شده از آخرین اسکن",
    sm_generated_help: "فقط صفحه‌های قابل ایندکس با پاسخ ۲۰۰ و canonical خودشان؛ بقیه کنار گذاشته می‌شوند.",
    sm_images: "با تصویرها",
    sm_urls: "نشانی",
    sm_lastmod: "با تاریخ به‌روزرسانی",
    sm_image_n: "تصویر",
    sm_files: "فایل‌ها",
    sm_excluded: "کنار گذاشته‌شده",
    sm_submit: "ارسال به Search Console",
    sm_submit_url: "نشانی نقشه‌ی سایت",
    sm_submitted: "نقشه‌ی سایت به Search Console ارسال شد؛ گوگل آن را در صف خواندن می‌گذارد.",
    sm_validate: "اعتبارسنجی نقشه‌های فعلی سایت",
    sm_validate_help: "نقشه‌های اعلام‌شده در robots.txt (یا نشانی‌ای که وارد می‌کنی) با آخرین اسکن مقایسه می‌شوند: هر نشانی باید ۲۰۰، قابل ایندکس و canonical خودش باشد.",
    sm_validate_url: "نشانی نقشه (اختیاری)",
    sm_validate_run: "اعتبارسنجی",
    sm_sources: "نقشه‌های خوانده‌شده",
    sm_listed: "{n} نشانی در نقشه‌ها",
    sm_truncated: "بیش از حد بررسی بود؛ فقط بخشی بررسی شد.",
    sm_problems: "مشکل نشانی‌ها",
    sm_examples: "نمونه‌ها",
    sm_status: "وضعیت",
    sm_kind: "نوع",
    sm_count: "تعداد",
    sm_no_problems: "همه‌ی نشانی‌های نقشه سالم‌اند.",
    sm_needs_gsc: "برای ارسال، Search Console را وصل کن.",
  },
  {
    nav_label: "Technical tools",
    t_schema: "Structured data",
    t_links: "Internal links",
    t_robots: "robots.txt",
    t_sitemap: "Sitemap",
    d_schema: "Build JSON-LD for articles, products, FAQs, local businesses and more, validate it, and put it on the site with approval.",
    d_links: "Each page's link equity, orphan pages, important pages with too few links, and link suggestions with anchor text.",
    d_robots: "The live file, a URL tester per crawler, an editor with a line-by-line diff and a warning for important pages that become blocked.",
    d_sitemap: "Build the sitemap from the latest scan, validate the existing ones, put it on the site and submit it to Search Console.",
    open_tool: "Open",
    page_url: "Page URL",
    load: "Load",
    apply_title: "Apply to the site",
    apply_help: "A sensitive fix proposal is created; once approved in the approval queue it is written through the same route as other fixes, and can be rolled back.",
    propose: "Create a fix proposal",
    target_cf: "Cloudflare edge",
    target_wp: "WordPress",
    target_ok: "{target} is connected and supports this change.",
    target_unsupported: "{target} is connected but cannot make this kind of change.",
    target_missing: "{target} is not connected.",
    download_file: "Download the file",
    issues: "Issues",
    no_issues: "No issues found.",
    line_n: "Line {n}",
    sc_pick_type: "Markup type",
    sc_existing: "The page's current markup",
    sc_existing_none: "The page had no JSON-LD markup in the latest scan.",
    sc_not_crawled: "This URL was not in the latest scan; to compare with existing markup, use the URL of a scanned page.",
    sc_prefilled: "Prefilled from the page:",
    sc_from_crawl: "the site scan",
    sc_from_markup: "the page's current markup",
    sc_form: "Details",
    sc_preview: "JSON-LD output",
    sc_validation: "Validation against Google's documentation",
    sc_conflicts: "Conflicts with the current markup",
    sc_valid: "No errors; ready to apply.",
    sc_has_errors: "Fix the errors before applying.",
    sc_render: "Preview in the panel's browser",
    sc_render_help: "The real page opens in the panel's browser with this markup added; nothing is written to the site.",
    sc_render_run: "Open the page with this markup",
    sc_render_types: "Types the page declares after this change:",
    sc_render_none: "No markup was found.",
    sc_paste: "Validate hand-written markup",
    sc_paste_help: "Paste JSON-LD written by hand or copied from elsewhere.",
    sc_paste_run: "Validate",
    sc_paste_invalid: "That text is not valid JSON.",
    sc_add_row: "Add a row",
    sc_fill_rows: "Required fields are empty in the rows: {f}",
    sc_remove_row: "Remove the row",
    sc_add_item: "Add",
    sc_type_n: "{t}",
    il_intro:
      "Each page's equity is PageRank over the internal links of the latest scan (0–100). An orphan page has no internal links to it; a weakly linked page earns Search Console clicks but receives little equity.",
    il_pages: "Pages",
    il_links: "Internal links",
    il_nofollow: "Nofollow links",
    il_orphans: "Orphan pages",
    il_weak: "Important, weakly linked",
    il_top_share: "Equity held by the strongest 10% of pages",
    il_histogram: "Inbound link distribution",
    il_histogram_help: "How many pages have how many internal links pointing to them.",
    il_top: "Most important pages",
    il_equity: "Equity",
    il_inlinks: "In",
    il_outlinks: "Out",
    il_depth: "Depth",
    il_clicks: "Clicks",
    il_suggestions: "Link suggestions",
    il_sugg_help: "Which strong page should link to which page, with anchor text taken from real queries or the page title.",
    il_from: "From",
    il_to: "To",
    il_anchor: "Anchor text",
    il_reason: "Why",
    il_none: "Nothing here.",
    il_page_view: "Inspect a page",
    il_inbound: "Inbound links",
    il_outbound: "Outbound links",
    il_link_from: "Pages that should link here",
    il_link_to: "Related pages this page could link to",
    il_not_indexable: "Not indexable",
    il_importance_gsc: "Importance from Search Console clicks",
    il_importance_none: "Search Console is not connected; weakly linked pages cannot be found by clicks.",
    il_scanned: "Latest scan {when}",
    rb_current: "Current file",
    rb_state_ok: "Reachable",
    rb_state_missing: "Missing (everything allowed)",
    rb_state_unreachable: "Unreachable (Google stops crawling)",
    rb_empty: "The file is empty.",
    rb_suggested: "The site has no robots.txt; a basic file is suggested.",
    rb_tester: "URL tester",
    rb_tester_help: "One URL or path per line. Answered by the same robots.txt parser the panel's crawler uses (`RFC 9309`).",
    rb_agents: "Crawlers",
    rb_agent_custom: "Another crawler",
    rb_against: "Against",
    rb_against_live: "The current file",
    rb_against_edit: "The edited version",
    rb_test_run: "Test",
    rb_allowed: "Allowed",
    rb_blocked: "Blocked",
    rb_rule: "Rule",
    rb_no_rule: "No rule matched (allowed)",
    rb_group: "Group",
    rb_editor: "Edit",
    rb_review: "Review changes",
    rb_diff: "Difference from the current file",
    rb_no_diff: "No change from the current file.",
    rb_newly_blocked: "Important pages this version blocks for Googlebot",
    rb_newly_blocked_help: "Blocking them makes this proposal need explicit approval.",
    rb_newly_allowed: "{n} pages blocked now become allowed with this version.",
    rb_checked: "{n} important URLs checked.",
    rb_reset: "Back to the current file",
    sm_generated: "Sitemap built from the latest scan",
    sm_generated_help: "Only indexable pages answering 200 that are their own canonical; everything else is left out.",
    sm_images: "Include images",
    sm_urls: "URLs",
    sm_lastmod: "With last-modified date",
    sm_image_n: "Images",
    sm_files: "Files",
    sm_excluded: "Left out",
    sm_submit: "Submit to Search Console",
    sm_submit_url: "Sitemap URL",
    sm_submitted: "The sitemap was submitted to Search Console; Google queues it for reading.",
    sm_validate: "Validate the site's current sitemaps",
    sm_validate_help: "The sitemaps declared in robots.txt (or the URL you enter) are checked against the latest scan: every URL should answer 200, be indexable and be its own canonical.",
    sm_validate_url: "Sitemap URL (optional)",
    sm_validate_run: "Validate",
    sm_sources: "Sitemaps read",
    sm_listed: "{n} URLs in the sitemaps",
    sm_truncated: "Too many to check; only part was checked.",
    sm_problems: "URL problems",
    sm_examples: "Examples",
    sm_status: "Status",
    sm_kind: "Kind",
    sm_count: "Count",
    sm_no_problems: "Every URL in the sitemaps is healthy.",
    sm_needs_gsc: "Connect Search Console to submit.",
  },
);

export type ToolStrings = (typeof TOOLS)["fa"];

/** Form labels for the schema generator's fields, keyed by property name. */
export const SCHEMA_FIELDS = defineDict(
  {
    name: "نام",
    legalName: "نام حقوقی",
    alternateName: "نام دیگر",
    url: "نشانی",
    logo: "نشانی لوگو",
    description: "توضیح",
    email: "ایمیل",
    telephone: "تلفن",
    sameAs: "صفحه‌های رسمی دیگر (شبکه‌های اجتماعی و …)",
    address: "نشانی پستی",
    streetAddress: "خیابان و پلاک",
    addressLocality: "شهر",
    addressRegion: "استان",
    postalCode: "کد پستی",
    addressCountry: "کشور (کد دوحرفی)",
    businessType: "نوع کسب‌وکار (مثلاً `Restaurant`)",
    image: "نشانی تصویر",
    priceRange: "بازه‌ی قیمت",
    geo: "مختصات",
    latitude: "عرض جغرافیایی",
    longitude: "طول جغرافیایی",
    openingHours: "ساعت کار",
    days: "روزها",
    opens: "از ساعت",
    closes: "تا ساعت",
    servesCuisine: "نوع غذا",
    menu: "نشانی منو",
    aggregateRating: "امتیاز کاربران",
    ratingValue: "امتیاز",
    ratingCount: "تعداد رأی",
    reviewCount: "تعداد نقد",
    bestRating: "بیشترین امتیاز",
    worstRating: "کمترین امتیاز",
    searchUrlTemplate: "الگوی نشانی جستجو (با `{search_term_string}`)",
    items: "موارد",
    headline: "تیتر",
    datePublished: "تاریخ انتشار",
    dateModified: "تاریخ به‌روزرسانی",
    authors: "نویسندگان",
    type: "نوع",
    publisher: "ناشر",
    sku: "کد کالا",
    gtin: "بارکد",
    mpn: "شماره‌ی قطعه‌ی سازنده",
    brand: "برند",
    offers: "پیشنهاد فروش",
    price: "قیمت",
    priceCurrency: "واحد پول (مثلاً `IRR`)",
    availability: "موجودی",
    priceValidUntil: "قیمت معتبر تا",
    validFrom: "معتبر از",
    itemCondition: "وضعیت کالا",
    question: "پرسش",
    answer: "پاسخ",
    totalTime: "زمان کل (مثلاً `PT30M`)",
    supplies: "مواد لازم",
    tools: "ابزارهای لازم",
    steps: "گام‌ها",
    text: "متن",
    jobTitle: "سمت",
    worksFor: "محل کار",
    startDate: "شروع",
    endDate: "پایان",
    eventStatus: "وضعیت رویداد",
    attendanceMode: "نحوه‌ی حضور",
    location: "مکان",
    organizer: "برگزارکننده",
    performer: "اجراکننده",
  },
  {
    name: "Name",
    legalName: "Legal name",
    alternateName: "Alternate name",
    url: "URL",
    logo: "Logo URL",
    description: "Description",
    email: "Email",
    telephone: "Telephone",
    sameAs: "Other official profiles (social media, …)",
    address: "Postal address",
    streetAddress: "Street address",
    addressLocality: "City",
    addressRegion: "Region",
    postalCode: "Postal code",
    addressCountry: "Country (two-letter code)",
    businessType: "Business type (e.g. `Restaurant`)",
    image: "Image URL",
    priceRange: "Price range",
    geo: "Coordinates",
    latitude: "Latitude",
    longitude: "Longitude",
    openingHours: "Opening hours",
    days: "Days",
    opens: "Opens",
    closes: "Closes",
    servesCuisine: "Cuisine",
    menu: "Menu URL",
    aggregateRating: "User rating",
    ratingValue: "Rating",
    ratingCount: "Number of ratings",
    reviewCount: "Number of reviews",
    bestRating: "Best rating",
    worstRating: "Worst rating",
    searchUrlTemplate: "Search URL template (with `{search_term_string}`)",
    items: "Items",
    headline: "Headline",
    datePublished: "Published",
    dateModified: "Modified",
    authors: "Authors",
    type: "Type",
    publisher: "Publisher",
    sku: "SKU",
    gtin: "GTIN",
    mpn: "MPN",
    brand: "Brand",
    offers: "Offer",
    price: "Price",
    priceCurrency: "Currency (e.g. `USD`)",
    availability: "Availability",
    priceValidUntil: "Price valid until",
    validFrom: "Valid from",
    itemCondition: "Condition",
    question: "Question",
    answer: "Answer",
    totalTime: "Total time (e.g. `PT30M`)",
    supplies: "Supplies",
    tools: "Tools",
    steps: "Steps",
    text: "Text",
    jobTitle: "Job title",
    worksFor: "Works for",
    startDate: "Start",
    endDate: "End",
    eventStatus: "Event status",
    attendanceMode: "Attendance",
    location: "Location",
    organizer: "Organizer",
    performer: "Performer",
  },
);

/** Values of the generator's enumerations. */
export const SCHEMA_ENUMS = defineDict(
  {
    InStock: "موجود",
    OutOfStock: "ناموجود",
    PreOrder: "پیش‌فروش",
    BackOrder: "سفارشی",
    Discontinued: "توقف تولید",
    LimitedAvailability: "موجودی محدود",
    SoldOut: "تمام شد",
    OnlineOnly: "فقط آنلاین",
    InStoreOnly: "فقط در فروشگاه",
    NewCondition: "نو",
    UsedCondition: "کارکرده",
    RefurbishedCondition: "بازسازی‌شده",
    DamagedCondition: "آسیب‌دیده",
    EventScheduled: "برنامه‌ریزی‌شده",
    EventCancelled: "لغو شده",
    EventPostponed: "به تعویق افتاده",
    EventRescheduled: "زمان‌بندی دوباره",
    EventMovedOnline: "آنلاین شد",
    offline: "حضوری",
    online: "آنلاین",
    mixed: "ترکیبی",
    Person: "شخص",
    Organization: "سازمان",
    Monday: "دوشنبه",
    Tuesday: "سه‌شنبه",
    Wednesday: "چهارشنبه",
    Thursday: "پنجشنبه",
    Friday: "جمعه",
    Saturday: "شنبه",
    Sunday: "یکشنبه",
    none: "—",
  },
  {
    InStock: "In stock",
    OutOfStock: "Out of stock",
    PreOrder: "Pre-order",
    BackOrder: "Back order",
    Discontinued: "Discontinued",
    LimitedAvailability: "Limited availability",
    SoldOut: "Sold out",
    OnlineOnly: "Online only",
    InStoreOnly: "In store only",
    NewCondition: "New",
    UsedCondition: "Used",
    RefurbishedCondition: "Refurbished",
    DamagedCondition: "Damaged",
    EventScheduled: "Scheduled",
    EventCancelled: "Cancelled",
    EventPostponed: "Postponed",
    EventRescheduled: "Rescheduled",
    EventMovedOnline: "Moved online",
    offline: "In person",
    online: "Online",
    mixed: "Mixed",
    Person: "Person",
    Organization: "Organization",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
    Sunday: "Sunday",
    none: "—",
  },
);
