import { defineDict } from "../../../lib/dict";

export const COMPETITORS = defineDict(
  {
    intro:
      "سایت‌های رقیب را اضافه کن تا خزنده‌ی خود پنل از هرکدام نمونه بردارد (تا ۳۰ صفحه، یک درخواست در ثانیه) و با همان روش کنار سایت تو مقایسه کند. شکاف کلمات کلیدی و بک‌لینک‌ها داده‌ی پولی DataForSEO است.",
    add_title: "افزودن رقیب",
    domain: "دامنه یا نشانی",
    domain_placeholder: "competitor.com",
    name: "نام (اختیاری)",
    add: "افزودن",
    added: "رقیب اضافه شد. برای مقایسه، تحلیل را اجرا کن.",
    limit: "{n} از {max}",
    list_title: "رقبا",
    empty: "هنوز رقیبی اضافه نشده. دامنه‌ی سایت‌هایی را که در نتایج جستجو با تو رقابت می‌کنند وارد کن.",
    analyze_all: "تحلیل همه",
    analyze: "تحلیل",
    analyzing: "در حال تحلیل…",
    analyzed: "آخرین تحلیل {when}",
    never_analyzed: "هنوز تحلیل نشده",
    sampled: "{n} صفحه نمونه",
    pages: "صفحه‌ها",
    remove: "حذف رقیب",
    analyze_started: "تحلیل در صف است؛ برای هر سایت چند دقیقه طول می‌کشد.",
    analyze_done: "تحلیل تمام شد.",
    analyze_site_failed: "نمونه‌برداری از {d} ناموفق بود.",
    analyze_failed: "تحلیل ناموفق بود. چند دقیقه‌ی دیگر دوباره تلاش کن.",
    // compare
    compare_title: "مقایسه با سایت تو",
    compare_help: "از آخرین نمونه‌ی هر سایت، با یک روش برای همه. صفحه‌های با پاسخ ۲۰۰ شمرده می‌شوند.",
    compare_empty: "برای مقایسه، دست‌کم یک رقیب اضافه و تحلیل کن.",
    ours: "سایت تو",
    not_sampled: "نمونه‌ای نیست",
    m_pages: "صفحه‌ی نمونه",
    m_ok: "صفحه‌ی سالم (۲۰۰)",
    m_words_median: "میانه‌ی تعداد کلمه",
    m_words_avg: "میانگین تعداد کلمه",
    m_title: "میانگین طول عنوان (نویسه)",
    m_desc: "میانگین طول توضیحات متا (نویسه)",
    m_no_desc: "صفحه‌ی بدون توضیحات متا",
    m_one_h1: "صفحه با دقیقاً یک H1",
    m_h2: "میانگین تعداد H2",
    m_internal: "میانگین لینک داخلی",
    m_external: "میانگین لینک خارجی",
    m_schema: "انواع نشانه‌گذاری ساختاریافته",
    m_lcp: "LCP صفحه‌ی اصلی (آزمایشگاهی)",
    m_cls: "CLS صفحه‌ی اصلی (آزمایشگاهی)",
    chart_words: "میانه‌ی تعداد کلمه",
    chart_links: "میانگین لینک داخلی در هر صفحه",
    // pages sheet
    pages_title: "صفحه‌های نمونه‌برداری‌شده",
    col_url: "نشانی",
    col_status: "وضعیت",
    col_title: "عنوان",
    col_words: "کلمه",
    col_h1: "H1",
    col_schema: "نشانه‌گذاری",
    no_pages: "هنوز نمونه‌ای برداشته نشده.",
    // gap
    gap_title: "شکاف کلمات کلیدی",
    gap_help:
      "کلمه‌هایی که رقیب در ۲۰ نتیجه‌ی اول برایشان رتبه دارد و تو نداری یا پایین‌تری — از داده‌ی رتبه‌بندی DataForSEO برای هر دو دامنه.",
    competitor: "رقیب",
    country: "کشور",
    language: "زبان",
    lang_fa: "فارسی",
    lang_en: "انگلیسی",
    run_gap: "یافتن شکاف",
    missing: "کلمه‌هایی که تو رتبه نداری",
    behind: "کلمه‌هایی که پایین‌تری",
    shared_n: "{n} کلمه‌ی مشترک",
    col_keyword: "کلمه",
    col_theirs: "جایگاه رقیب",
    col_ours: "جایگاه تو",
    col_volume: "حجم",
    col_kd: "سختی",
    none_found: "موردی پیدا نشد.",
    // backlinks
    bl_title: "بک‌لینک‌ها",
    bl_help: "خلاصه‌ی بک‌لینک‌های سایت تو و رقیب از DataForSEO (اشتراک جداگانه‌ی بک‌لینک لازم است).",
    run_bl: "مقایسه‌ی بک‌لینک‌ها",
    bl_backlinks: "بک‌لینک",
    bl_domains: "دامنه‌ی ارجاع‌دهنده",
    bl_main: "دامنه‌ی اصلی ارجاع‌دهنده",
    bl_broken: "بک‌لینک خراب",
    bl_rank: "رتبه‌ی اعتبار (۰ تا ۱۰۰۰)",
    bl_spam: "امتیاز اسپم",
    pick_competitor: "یک رقیب انتخاب کن",
  },
  {
    intro:
      "Add competing sites and the panel's own crawler samples each (up to 30 pages, one request a second) and compares them with your site by the same method. Keyword gap and backlinks are paid DataForSEO data.",
    add_title: "Add a competitor",
    domain: "Domain or URL",
    domain_placeholder: "competitor.com",
    name: "Name (optional)",
    add: "Add",
    added: "Competitor added. Run an analysis to compare.",
    limit: "{n} of {max}",
    list_title: "Competitors",
    empty: "No competitors yet. Enter the domains of the sites you compete with in search results.",
    analyze_all: "Analyze all",
    analyze: "Analyze",
    analyzing: "Analyzing…",
    analyzed: "Last analyzed {when}",
    never_analyzed: "Not analyzed yet",
    sampled: "{n} pages sampled",
    pages: "Pages",
    remove: "Remove competitor",
    analyze_started: "Analysis queued; it takes a few minutes per site.",
    analyze_done: "Analysis finished.",
    analyze_site_failed: "Sampling {d} failed.",
    analyze_failed: "The analysis failed. Try again in a few minutes.",
    compare_title: "Compared with your site",
    compare_help: "From each site's latest sample, by the same method for all. Pages answering 200 are counted.",
    compare_empty: "Add and analyze at least one competitor to compare.",
    ours: "Your site",
    not_sampled: "No sample",
    m_pages: "Pages sampled",
    m_ok: "Healthy pages (200)",
    m_words_median: "Median word count",
    m_words_avg: "Average word count",
    m_title: "Average title length (characters)",
    m_desc: "Average meta description length (characters)",
    m_no_desc: "Pages without a meta description",
    m_one_h1: "Pages with exactly one H1",
    m_h2: "Average H2 count",
    m_internal: "Average internal links",
    m_external: "Average external links",
    m_schema: "Structured data types",
    m_lcp: "Homepage LCP (lab)",
    m_cls: "Homepage CLS (lab)",
    chart_words: "Median word count",
    chart_links: "Average internal links per page",
    pages_title: "Sampled pages",
    col_url: "URL",
    col_status: "Status",
    col_title: "Title",
    col_words: "Words",
    col_h1: "H1",
    col_schema: "Markup",
    no_pages: "No sample taken yet.",
    gap_title: "Keyword gap",
    gap_help:
      "Keywords the competitor ranks for in the top 20 where you don't rank or rank lower — from DataForSEO ranking data for both domains.",
    competitor: "Competitor",
    country: "Country",
    language: "Language",
    lang_fa: "Persian",
    lang_en: "English",
    run_gap: "Find the gap",
    missing: "Keywords you don't rank for",
    behind: "Keywords where you rank lower",
    shared_n: "{n} shared keywords",
    col_keyword: "Keyword",
    col_theirs: "Their position",
    col_ours: "Your position",
    col_volume: "Volume",
    col_kd: "Difficulty",
    none_found: "Nothing found.",
    bl_title: "Backlinks",
    bl_help: "Backlink summary for your site and the competitor from DataForSEO (needs the separate Backlinks subscription).",
    run_bl: "Compare backlinks",
    bl_backlinks: "Backlinks",
    bl_domains: "Referring domains",
    bl_main: "Referring main domains",
    bl_broken: "Broken backlinks",
    bl_rank: "Authority rank (0–1000)",
    bl_spam: "Spam score",
    pick_competitor: "Pick a competitor",
  },
);

export type CompetitorStrings = (typeof COMPETITORS)["fa"];
