import type { MessageKey } from "../../../lib/i18n";

/** The strings the browser screen's client component needs, translated on the server. */
export const BROWSER_KEYS = [
  "br_privacy",
  "br_address",
  "br_address_placeholder",
  "br_go",
  "br_back",
  "br_forward",
  "br_reload",
  "br_device",
  "br_desktop",
  "br_mobile",
  "br_open",
  "br_start_hint",
  "br_starting",
  "br_loading_page",
  "br_ended",
  "br_restart",
  "br_close",
  "br_closed",
  "br_viewport",
  "br_keyboard_hint",
  "br_copied",
  "br_no_permission",
  "br_unavailable",
  "br_busy",
  "br_blocked",
  "br_err_name",
  "br_err_unreachable",
  "br_err_refused",
  "br_err_timeout",
  "br_err_cert",
  "br_err_generic",
  "br_untitled",
  "br_inspect",
  "br_inspect_hint",
  "br_inspect_run",
  "br_inspect_running",
  "br_inspect_again",
  "br_inspected_url",
  "br_http_status",
  "br_timed_out",
  "br_js_risks",
  "br_js_ok",
  "br_js_unavailable",
  "br_js_title",
  "br_js_description",
  "br_js_canonical",
  "br_js_robots",
  "br_js_h1",
  "br_js_links",
  "br_seo",
  "br_title",
  "br_description",
  "br_canonical",
  "br_robots",
  "br_h1",
  "br_lang",
  "br_hreflang",
  "br_jsonld",
  "br_links",
  "br_links_value",
  "br_missing_alt",
  "br_words",
  "br_none",
  "br_chars",
  "br_metrics",
  "br_metrics_note",
  "br_lcp",
  "br_cls",
  "br_ttfb",
  "br_seconds",
  "br_ms",
  "br_good",
  "br_needs_work",
  "br_poor",
  "br_not_measured",
  "br_console",
  "br_console_none",
  "br_exception",
  "br_blocked_requests",
  "br_screenshot",
] as const satisfies readonly MessageKey[];

export type BrowserKey = (typeof BROWSER_KEYS)[number];
export type BrowserStrings = Record<BrowserKey, string>;
