import { defineDict } from "../../../lib/dict";

export const REPORTS = defineDict(
  {
    pdf_title: "گزارش‌های PDF",
    pdf_intro: "گزارش آماده‌ی ارائه به مدیر یا مشتری، با نام و رنگ و لوگوی سازمان تو، به فارسی یا انگلیسی. ساخت آن در پس‌زمینه انجام می‌شود و وقتی آماده شد اعلان می‌گیری.",
    kind: "نوع گزارش",
    language: "زبان گزارش",
    lang_fa: "فارسی",
    lang_en: "انگلیسی",
    generate: "ساختن گزارش",
    generating: "در حال ساخت…",
    queued: "گزارش در صف ساخت است.",
    ready: "گزارش آماده شد.",
    failed: "ساخت گزارش ناموفق بود.",
    list: "گزارش‌های ساخته‌شده",
    empty: "هنوز گزارشی ساخته نشده.",
    col_file: "فایل",
    col_kind: "نوع",
    col_size: "حجم",
    col_created: "ساخته‌شده",
    open: "نمایش",
    download: "دانلود",
    pending: "در حال ساخت",
    brand_title: "نشان تجاری گزارش‌ها",
    brand_intro: "برای همه‌ی پروژه‌های این سازمان به کار می‌رود.",
    brand_name: "نام روی گزارش",
    brand_name_default: "پیش‌فرض: {name}",
    brand_color: "رنگ اصلی",
    brand_logo: "لوگو",
    brand_logo_pick: "انتخاب تصویر",
    brand_logo_help: "`PNG`، `JPEG`، `WebP` یا `SVG` تا ۳۰۰ کیلوبایت.",
    brand_logo_too_big: "حجم لوگو بیش از ۳۰۰ کیلوبایت است.",
    brand_logo_type: "این قالب تصویر پذیرفته نیست.",
    brand_remove_logo: "برداشتن لوگو",
    brand_save: "ذخیره‌ی نشان تجاری",
    brand_saved: "نشان تجاری ذخیره شد.",
    brand_preview: "پیش‌نمایش سربرگ",
    live_title: "وضعیت همین حالا",
  },
  {
    pdf_title: "PDF reports",
    pdf_intro: "A report ready for a manager or client, with your organization's name, colour and logo, in Persian or English. It is built in the background and you are notified when it is ready.",
    kind: "Report type",
    language: "Report language",
    lang_fa: "Persian",
    lang_en: "English",
    generate: "Generate report",
    generating: "Generating…",
    queued: "The report is queued.",
    ready: "The report is ready.",
    failed: "The report could not be generated.",
    list: "Generated reports",
    empty: "No reports yet.",
    col_file: "File",
    col_kind: "Type",
    col_size: "Size",
    col_created: "Created",
    open: "View",
    download: "Download",
    pending: "Generating",
    brand_title: "Report branding",
    brand_intro: "Used for every project in this organization.",
    brand_name: "Name on the report",
    brand_name_default: "Default: {name}",
    brand_color: "Main colour",
    brand_logo: "Logo",
    brand_logo_pick: "Choose an image",
    brand_logo_help: "`PNG`, `JPEG`, `WebP` or `SVG` up to 300 KB.",
    brand_logo_too_big: "The logo is larger than 300 KB.",
    brand_logo_type: "That image format is not accepted.",
    brand_remove_logo: "Remove logo",
    brand_save: "Save branding",
    brand_saved: "Branding saved.",
    brand_preview: "Header preview",
    live_title: "Status right now",
  },
);

export type ReportStrings = (typeof REPORTS)["fa"];
