import { defineDict } from "../../../lib/dict";

export const KEYWORDS = defineDict(
  {
    title: "کلمات کلیدی و رتبه‌ها",
    intro: "کلمه‌هایی که برای این سایت مهم‌اند را ردیابی کن: جایگاه در گوگل، کلیک و نمایش، و اینکه کدام صفحه برایشان رتبه می‌گیرد.",
    add: "افزودن کلمه",
    sync: "همگام‌سازی رتبه‌ها",
    syncing: "در حال همگام‌سازی…",
    sync_gsc: "Search Console: {k} کلمه، {r} ردیف داده",
    sync_gsc_off: "Search Console وصل نیست؛ رتبه‌ای از آن گرفته نشد.",
    sync_dfs: "رتبه‌ی زنده: {n} کلمه بررسی شد، هزینه {cost} دلار",
    sync_dfs_failed: "{n} بررسی ناموفق بود",
    sync_failed: "همگام‌سازی ناموفق بود. چند دقیقه‌ی دیگر دوباره تلاش کن.",
    // stats
    st_tracked: "کلمه‌ی ردیابی‌شده",
    st_avg_pos: "میانگین جایگاه",
    st_clicks: "کلیک ۷ روز اخیر",
    st_impr: "نمایش ۷ روز اخیر",
    st_top10: "در ده نتیجه‌ی اول",
    st_visibility: "شاخص دیده‌شدن",
    // overview
    vis_title: "دیده‌شدن در جستجو",
    vis_help:
      "سهم کلیک‌هایی که جایگاه فعلی کلمه‌های ردیابی‌شده می‌تواند بگیرد، وزن‌دار با نمایش واقعی هر کلمه. ۱۰۰ یعنی همه در جایگاه اول.",
    vis_empty: "هنوز داده‌ی روزانه‌ای از Search Console برای کلمه‌های ردیابی‌شده نیامده است.",
    vis_axis: "شاخص دیده‌شدن در طول زمان",
    movers_title: "بیشترین جابه‌جایی",
    movers_sub: "۷ روز اخیر در برابر ۷ روز قبل",
    gains: "بهتر شده",
    losses: "بدتر شده",
    no_movers: "در این بازه جابه‌جایی چشمگیری دیده نشد.",
    vanished: "از نتایج بیرون رفت",
    // tabs
    tab_tracked: "ردیابی‌شده",
    tab_opps: "فرصت‌ها",
    tab_research: "یافتن کلمه",
    tab_mapping: "نگاشت و هم‌نوع‌خواری",
    tabs_label: "بخش‌های کلمات کلیدی",
    // tracked table
    q_placeholder: "جستجو در کلمه‌ها",
    tag_all: "همه‌ی برچسب‌ها",
    sort_label: "مرتب‌سازی",
    sort_recent: "تازه‌ترین",
    sort_position: "بهترین جایگاه",
    sort_clicks: "بیشترین کلیک",
    sort_impr: "بیشترین نمایش",
    sort_phrase: "الفبایی",
    active: "فعال",
    archived: "بایگانی",
    col_keyword: "کلمه",
    col_pos_gsc: "جایگاه",
    col_pos_serp: "رتبه‌ی زنده",
    col_change: "تغییر",
    col_clicks: "کلیک",
    col_impr: "نمایش",
    col_ctr: "نرخ کلیک",
    col_url: "صفحه‌ی رتبه‌گرفته",
    col_volume: "حجم جستجو",
    col_kd: "سختی",
    not_in_top100: "بیرون از ۱۰۰",
    no_data_yet: "هنوز داده‌ای نیامده",
    target_differs: "با صفحه‌ی هدف فرق دارد",
    target_matches: "همان صفحه‌ی هدف",
    empty_tracked: "هنوز کلمه‌ای ردیابی نمی‌شود. چند کلمه اضافه کن یا از فرصت‌های Search Console شروع کن.",
    empty_archived: "بایگانی خالی است.",
    empty_filtered: "هیچ کلمه‌ای با این پالایش پیدا نشد.",
    gsc_basis: "میانگین وزن‌دار ۷ روز آخری که داده دارد",
    // bulk
    bulk_archive: "بایگانی",
    bulk_unarchive: "بازگرداندن از بایگانی",
    bulk_delete: "حذف",
    bulk_add_tag: "افزودن برچسب",
    bulk_remove_tag: "برداشتن برچسب",
    tag_placeholder: "برچسب",
    bulk_done: "{n} کلمه به‌روز شد.",
    select_row: "انتخاب {k}",
    // add dialog
    add_title: "افزودن کلمات کلیدی",
    add_phrases: "کلمه‌ها (هر خط یکی)",
    add_placeholder: "خرید گوشی\nقیمت لپ‌تاپ",
    add_help: "تا ۵۰۰ کلمه در هر بار. کلمه‌های تکراری نادیده گرفته می‌شوند.",
    country: "کشور",
    language: "زبان",
    lang_fa: "فارسی",
    lang_en: "انگلیسی",
    device: "دستگاه",
    device_any: "همه‌ی دستگاه‌ها",
    device_desktop: "رایانه",
    device_mobile: "موبایل",
    tags: "برچسب‌ها",
    tags_help: "با ویرگول جدا کن.",
    add_submit: "افزودن",
    add_result: "{added} کلمه اضافه شد؛ {skipped} تکراری بود.",
    add_count: "{n} کلمه",
    // detail
    range: "بازه",
    days_n: "{n} روز",
    pos_chart: "جایگاه در طول زمان",
    pos_chart_help: "عدد کوچک‌تر بهتر است؛ جایگاه ۱ بالای نمودار است.",
    traffic_chart: "کلیک و نمایش",
    no_history: "برای این بازه داده‌ای نیست.",
    series_gsc: "Search Console (میانگین)",
    series_serp: "رتبه‌ی زنده",
    series_clicks: "کلیک",
    series_impr: "نمایش",
    target_url: "صفحه‌ی هدف",
    target_help: "صفحه‌ای که می‌خواهی برای این کلمه رتبه بگیرد؛ اگر صفحه‌ی دیگری رتبه بگیرد هشدار می‌بینی.",
    ranking_url: "صفحه‌ای که الان رتبه گرفته",
    serp_features: "بخش‌های ویژه‌ی صفحه‌ی نتایج",
    archive: "بایگانی",
    unarchive: "بازگرداندن",
    delete_kw: "حذف کلمه و تاریخچه",
    market: "{country} · {lang}",
    // opportunities
    opp_title: "فرصت‌های Search Console",
    opp_help:
      "جستجوهایی که سایت همین حالا در جایگاه ۴ تا ۲۰ برایشان نمایش می‌گیرد اما هنوز ردیابی نمی‌شوند — ارزان‌ترین رتبه‌ها برای بهتر کردن.",
    opp_potential: "کلیک اضافه‌ی ماهانه",
    opp_potential_help: "اگر به جایگاه ۳ برسد، با منحنی نرخ کلیک رایج؛ تخمین است، نه وعده.",
    opp_query: "جستجو",
    opp_empty: "در ۲۸ روز اخیر فرصتی با دست‌کم ۲۰ نمایش پیدا نشد.",
    track: "ردیابی",
    track_selected: "ردیابی موارد انتخاب‌شده",
    tracked: "ردیابی می‌شود",
    period: "از {from} تا {to}",
    // research
    seed: "کلمه‌ی پایه",
    seed_placeholder: "مثلاً: خرید مبل",
    suggest: "پیشنهاد بگیر",
    sugg_title: "پیشنهادهای جستجوی گوگل",
    sugg_note: "پیشنهاد — بدون داده‌ی حجم جستجو. همان چیزی است که گوگل هنگام تایپ پیشنهاد می‌دهد.",
    sugg_empty: "گوگل برای این کلمه پیشنهادی نداد.",
    ideas_title: "حجم جستجو و سختی",
    ideas_run: "گرفتن حجم و سختی",
    ideas_help: "ایده‌های کلمه با حجم ماهانه، سختی (۰ تا ۱۰۰) و هزینه‌ی هر کلیک از DataForSEO. نتیجه ۳۰ روز نگه داشته می‌شود.",
    ideas_empty: "DataForSEO برای این کلمه ایده‌ای برنگرداند.",
    col_idea: "ایده",
    col_cpc: "هزینه‌ی هر کلیک",
    // mapping
    map_title: "نگاشت کلمه به صفحه",
    map_help: "برای هر کلمه، صفحه‌ی هدفی که تعیین کرده‌ای در برابر صفحه‌ای که گوگل واقعاً نشان می‌دهد.",
    map_no_target: "هدفی تعیین نشده",
    map_no_rank: "هنوز رتبه‌ای ندارد",
    map_ok: "درست",
    map_wrong: "صفحه‌ی دیگری رتبه گرفته",
    map_unknown: "قابل مقایسه نیست",
    map_empty: "هنوز کلمه‌ای ردیابی نمی‌شود.",
    cannib_title: "هم‌نوع‌خواری کلمات",
    cannib_help:
      "جستجوهایی که چند صفحه‌ی سایت سهم واقعی از نمایش آن را بین خود تقسیم کرده‌اند؛ معمولاً به ضرر هر دو صفحه است. یکی را صفحه‌ی اصلی کن و بقیه را به آن لینک بده یا ادغام کن.",
    cannib_empty: "در ۲۸ روز اخیر هیچ جستجویی میان چند صفحه تقسیم نشده است.",
    share: "سهم نمایش",
    avg_pos: "جایگاه",
  },
  {
    title: "Keywords & rankings",
    intro: "Track the keywords that matter to this site: Google position, clicks and impressions, and which page ranks for them.",
    add: "Add keywords",
    sync: "Sync rankings",
    syncing: "Syncing…",
    sync_gsc: "Search Console: {k} keywords, {r} rows of data",
    sync_gsc_off: "Search Console is not connected; no positions came from it.",
    sync_dfs: "Live rankings: {n} keywords checked, cost ${cost}",
    sync_dfs_failed: "{n} checks failed",
    sync_failed: "The sync failed. Try again in a few minutes.",
    st_tracked: "Tracked keywords",
    st_avg_pos: "Average position",
    st_clicks: "Clicks, last 7 days",
    st_impr: "Impressions, last 7 days",
    st_top10: "In the top 10",
    st_visibility: "Visibility index",
    vis_title: "Search visibility",
    vis_help:
      "The share of clicks the tracked keywords' current positions can capture, weighted by each keyword's real impressions. 100 means all at #1.",
    vis_empty: "No daily Search Console data for the tracked keywords yet.",
    vis_axis: "Visibility index over time",
    movers_title: "Biggest movers",
    movers_sub: "Last 7 days vs the 7 before",
    gains: "Improved",
    losses: "Declined",
    no_movers: "No notable movement in this window.",
    vanished: "Dropped out",
    tab_tracked: "Tracked",
    tab_opps: "Opportunities",
    tab_research: "Find keywords",
    tab_mapping: "Mapping & cannibalization",
    tabs_label: "Keyword sections",
    q_placeholder: "Search keywords",
    tag_all: "All tags",
    sort_label: "Sort",
    sort_recent: "Newest",
    sort_position: "Best position",
    sort_clicks: "Most clicks",
    sort_impr: "Most impressions",
    sort_phrase: "Alphabetical",
    active: "Active",
    archived: "Archived",
    col_keyword: "Keyword",
    col_pos_gsc: "Position",
    col_pos_serp: "Live rank",
    col_change: "Change",
    col_clicks: "Clicks",
    col_impr: "Impressions",
    col_ctr: "CTR",
    col_url: "Ranking page",
    col_volume: "Search volume",
    col_kd: "Difficulty",
    not_in_top100: "Not in top 100",
    no_data_yet: "No data yet",
    target_differs: "Differs from the target",
    target_matches: "The target page",
    empty_tracked: "No keywords are tracked yet. Add a few, or start from the Search Console opportunities.",
    empty_archived: "The archive is empty.",
    empty_filtered: "No keyword matches this filter.",
    gsc_basis: "Weighted average of the last 7 days with data",
    bulk_archive: "Archive",
    bulk_unarchive: "Restore from archive",
    bulk_delete: "Delete",
    bulk_add_tag: "Add tag",
    bulk_remove_tag: "Remove tag",
    tag_placeholder: "Tag",
    bulk_done: "{n} keywords updated.",
    select_row: "Select {k}",
    add_title: "Add keywords",
    add_phrases: "Keywords (one per line)",
    add_placeholder: "buy running shoes\nbest laptop 2026",
    add_help: "Up to 500 at a time. Duplicates are skipped.",
    country: "Country",
    language: "Language",
    lang_fa: "Persian",
    lang_en: "English",
    device: "Device",
    device_any: "All devices",
    device_desktop: "Desktop",
    device_mobile: "Mobile",
    tags: "Tags",
    tags_help: "Separate with commas.",
    add_submit: "Add",
    add_result: "{added} added; {skipped} were duplicates.",
    add_count: "{n} keywords",
    range: "Range",
    days_n: "{n} days",
    pos_chart: "Position over time",
    pos_chart_help: "Lower is better; position 1 is at the top of the chart.",
    traffic_chart: "Clicks and impressions",
    no_history: "No data for this range.",
    series_gsc: "Search Console (average)",
    series_serp: "Live rank",
    series_clicks: "Clicks",
    series_impr: "Impressions",
    target_url: "Target page",
    target_help: "The page you want to rank for this keyword; you are warned when another page ranks instead.",
    ranking_url: "The page ranking now",
    serp_features: "Special results on the page",
    archive: "Archive",
    unarchive: "Restore",
    delete_kw: "Delete keyword and history",
    market: "{country} · {lang}",
    opp_title: "Search Console opportunities",
    opp_help:
      "Queries the site already appears for at positions 4–20 that are not tracked yet — the cheapest rankings to improve.",
    opp_potential: "Extra clicks / month",
    opp_potential_help: "If it reached position 3, by a common CTR curve; an estimate, not a promise.",
    opp_query: "Query",
    opp_empty: "No opportunity with at least 20 impressions in the last 28 days.",
    track: "Track",
    track_selected: "Track selected",
    tracked: "Tracked",
    period: "{from} to {to}",
    seed: "Seed keyword",
    seed_placeholder: "e.g. running shoes",
    suggest: "Get suggestions",
    sugg_title: "Google search suggestions",
    sugg_note: "Suggestions — no search volume data. These are what Google suggests while typing.",
    sugg_empty: "Google had no suggestions for this keyword.",
    ideas_title: "Search volume and difficulty",
    ideas_run: "Get volume and difficulty",
    ideas_help: "Keyword ideas with monthly volume, difficulty (0–100) and cost per click from DataForSEO. Results are kept for 30 days.",
    ideas_empty: "DataForSEO returned no ideas for this keyword.",
    col_idea: "Idea",
    col_cpc: "Cost per click",
    map_title: "Keyword-to-page mapping",
    map_help: "For each keyword, the target page you set against the page Google actually shows.",
    map_no_target: "No target set",
    map_no_rank: "Not ranking yet",
    map_ok: "Correct",
    map_wrong: "Another page ranks",
    map_unknown: "Nothing to compare",
    map_empty: "No keywords are tracked yet.",
    cannib_title: "Keyword cannibalization",
    cannib_help:
      "Queries whose impressions several of the site's pages split between them; usually bad for both. Make one the primary page and link the others to it, or merge them.",
    cannib_empty: "No query was split across several pages in the last 28 days.",
    share: "Impression share",
    avg_pos: "Position",
  },
);

export type KeywordStrings = (typeof KEYWORDS)["fa"];
