import { defineDict } from "./dict";

/**
 * Wording every SEO data screen shares: actions, states, data sources and the
 * "not configured" explanations. Screens receive it as `c` next to their own `s`.
 */
export const COMMON = defineDict(
  {
    loading: "در حال بارگذاری…",
    retry: "تلاش دوباره",
    save: "ذخیره",
    saving: "در حال ذخیره…",
    saved: "ذخیره شد.",
    cancel: "انصراف",
    close: "بستن",
    delete: "حذف",
    remove: "برداشتن",
    add: "افزودن",
    edit: "ویرایش",
    apply: "اعمال",
    run_now: "اجرا همین حالا",
    refresh: "بازآوری",
    download: "دانلود",
    preview: "پیش‌نمایش",
    copy: "رونوشت",
    copied: "رونوشت شد",
    back: "بازگشت",
    all: "همه",
    none: "هیچ",
    yes: "بله",
    no: "خیر",
    search: "جستجو",
    filter: "پالایش",
    more: "بیشتر",
    open: "باز کردن",
    details: "جزئیات",
    confirm_delete: "حذف شود؟ این کار برگشت‌پذیر نیست.",
    confirm: "مطمئنم",
    never: "هرگز",
    unknown: "نامشخص",
    select_all: "انتخاب همه",
    selected_n: "{n} مورد انتخاب شده",
    page: "صفحه",
    pages: "صفحه‌ها",
    url: "نشانی",
    date: "تاریخ",
    updated: "به‌روزرسانی",
    last_run: "آخرین اجرا",
    next_run: "اجرای بعدی",
    state_waiting: "در صف",
    state_active: "در حال اجرا",
    state_completed: "انجام شد",
    state_failed: "ناموفق",
    state_delayed: "به تعویق افتاد",
    job_started: "درخواست ثبت شد و در صف اجراست.",
    job_deduplicated: "یک اجرای مشابه در جریان است؛ همان ادامه پیدا می‌کند.",
    job_done: "کار تمام شد و داده‌ها تازه شدند.",
    job_slow: "هنوز در جریان است؛ نتیجه پس از پایان اینجا نمایش داده می‌شود.",
    no_project: "هنوز پروژه‌ای نساخته‌ای. اول یک سایت اضافه کن.",
    add_site: "افزودن سایت",
    no_permission: "نقش شما اجازهٔ این کار را ندارد.",
    read_only: "فقط مشاهده — نقش شما اجازهٔ تغییر ندارد.",
    // Data sources — every number on these screens names where it came from.
    src_gsc: "Search Console",
    src_gsc_long: "داده‌ی واقعی Search Console",
    src_serp: "نتایج زنده‌ی گوگل",
    src_dataforseo: "DataForSEO",
    src_autocomplete: "پیشنهاد گوگل",
    src_psi: "PageSpeed Insights",
    src_crawl: "خزش خود پنل",
    src_field: "داده‌ی کاربران واقعی",
    src_lab: "آزمایشگاهی",
    // Not configured / not connected
    nc_gsc_title: "Search Console وصل نیست",
    nc_gsc_body:
      "رتبه، کلیک و نمایش از داده‌ی واقعی Search Console می‌آید. تا وصل نشود این بخش عددی نشان نمی‌دهد — هیچ عددی ساختگی نیست.",
    nc_gsc_action: "وصل کردن Search Console",
    nc_dfs_title: "DataForSEO تنظیم نشده",
    nc_dfs_body:
      "حجم جستجو، سختی، رتبه‌ی زنده و بک‌لینک‌ها داده‌ی پولی DataForSEO است. مدیر سازمان می‌تواند حساب را در تنظیمات ← سرویس‌ها وارد کند؛ تا آن زمان این بخش خالی می‌ماند.",
    nc_dfs_action: "تنظیمات سرویس‌ها",
    nc_dfs_ask_admin: "از مالک یا مدیر سازمان بخواه DataForSEO را در تنظیمات ← سرویس‌ها وصل کند.",
    paid_note: "درخواست پولی — هزینه پس از اجرا نمایش داده می‌شود.",
    cost_usd: "هزینه: {n} دلار",
    cost_cached: "از حافظه؛ بدون هزینه",
    usd: "{n} دلار",
    no_scan_title: "هنوز اسکنی انجام نشده",
    no_scan_body: "این ابزار از داده‌ی آخرین اسکن سایت ساخته می‌شود. یک اسکن اجرا کن و برگرد.",
    needs_rescan: "آخرین اسکن پیش از ثبت جزئیات صفحه‌ها انجام شده؛ یک اسکن تازه اجرا کن.",
    go_audit: "رفتن به اسکن",
    proposal_created: "پیشنهاد اصلاح ساخته شد و برای تأیید در صف است.",
    open_proposal: "مشاهده‌ی پیشنهاد",
    manual_only:
      "مسیر اعمال فعلی نمی‌تواند این تغییر را روی سایت بنویسد. فایل را دانلود کن و دستی بارگذاری کن، یا Cloudflare را وصل کن.",
    connect_site: "اتصال سایت",
    via_target: "مسیر اعمال: {target}",
  },
  {
    loading: "Loading…",
    retry: "Try again",
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    cancel: "Cancel",
    close: "Close",
    delete: "Delete",
    remove: "Remove",
    add: "Add",
    edit: "Edit",
    apply: "Apply",
    run_now: "Run now",
    refresh: "Refresh",
    download: "Download",
    preview: "Preview",
    copy: "Copy",
    copied: "Copied",
    back: "Back",
    all: "All",
    none: "None",
    yes: "Yes",
    no: "No",
    search: "Search",
    filter: "Filter",
    more: "More",
    open: "Open",
    details: "Details",
    confirm_delete: "Delete it? This cannot be undone.",
    confirm: "I'm sure",
    never: "Never",
    unknown: "Unknown",
    select_all: "Select all",
    selected_n: "{n} selected",
    page: "Page",
    pages: "Pages",
    url: "URL",
    date: "Date",
    updated: "Updated",
    last_run: "Last run",
    next_run: "Next run",
    state_waiting: "Queued",
    state_active: "Running",
    state_completed: "Done",
    state_failed: "Failed",
    state_delayed: "Delayed",
    job_started: "Requested — it is in the queue.",
    job_deduplicated: "A run like this is already in progress; that one continues.",
    job_done: "Finished; the data below is fresh.",
    job_slow: "Still running; the result appears here when it finishes.",
    no_project: "There is no project yet. Add a site first.",
    add_site: "Add a site",
    no_permission: "Your role does not allow that.",
    read_only: "View only — your role cannot change this.",
    src_gsc: "Search Console",
    src_gsc_long: "Real Search Console data",
    src_serp: "Live Google results",
    src_dataforseo: "DataForSEO",
    src_autocomplete: "Google suggestions",
    src_psi: "PageSpeed Insights",
    src_crawl: "The panel's own crawl",
    src_field: "Real-user data",
    src_lab: "Lab",
    nc_gsc_title: "Search Console is not connected",
    nc_gsc_body:
      "Positions, clicks and impressions come from real Search Console data. Until it is connected this section shows no numbers — nothing here is ever made up.",
    nc_gsc_action: "Connect Search Console",
    nc_dfs_title: "DataForSEO is not set up",
    nc_dfs_body:
      "Search volume, difficulty, live rankings and backlinks are paid DataForSEO data. An organization admin can add the account under Settings → Integrations; until then this section stays empty.",
    nc_dfs_action: "Integration settings",
    nc_dfs_ask_admin: "Ask an owner or admin of the organization to connect DataForSEO under Settings → Integrations.",
    paid_note: "Paid request — the cost is shown after it runs.",
    cost_usd: "Cost: ${n}",
    cost_cached: "From cache; no cost",
    usd: "${n}",
    no_scan_title: "No scan yet",
    no_scan_body: "This tool is built from the latest scan of the site. Run a scan and come back.",
    needs_rescan: "The latest scan predates page details being recorded; run a fresh scan.",
    go_audit: "Go to scans",
    proposal_created: "A fix proposal was created and is waiting for approval.",
    open_proposal: "View the proposal",
    manual_only:
      "The current write route cannot put this change on the site. Download the file and upload it by hand, or connect Cloudflare.",
    connect_site: "Connect site",
    via_target: "Write route: {target}",
  },
);

export type CommonStrings = (typeof COMMON)["fa"];
